package ve

// ASCII art generated by: https://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow (with modified 'S' for readability)

import hm "container/handle_map"
import "core:c"
import sm "core:container/small_array"
import "core:fmt"
import "core:log"
import "core:math/linalg/glsl"
import "core:mem"
import "lib/shaderc"
import "lib/vma"
import "math"
import "vendor:glfw"
import tt "vendor:stb/truetype"
import vk "vendor:vulkan"

Sample_Count_Flags :: vk.SampleCountFlags
Sample_Count_Flag :: vk.SampleCountFlag
Sampler :: vk.Sampler
Semaphore :: vk.Semaphore
Push_Constant_Range :: vk.PushConstantRange
Device_Size :: vk.DeviceSize
Command_Buffer :: vk.CommandBuffer
Pipeline_Stage_Flags :: vk.PipelineStageFlags
Descriptor_Set :: vk.DescriptorSet


Buildin_Resource :: struct {
	pipeline:    struct {
		default_h:   Render_Pipeline_Handle,
		primitive_h: Render_Pipeline_Handle,
		text_h:      Render_Pipeline_Handle,
	},
	square:      Model, // TODO: depricated
	unit_square: Mesh,
}

Vulkan_State :: struct {
	enabled_layer_names:      [dynamic]cstring,
	instance:                 vk.Instance,
	physical_device:          vk.PhysicalDevice,
	physical_device_property: vk.PhysicalDeviceProperties,
	memory_propertices:       vk.PhysicalDeviceMemoryProperties,
	device:                   vk.Device,
	dbg_messenger:            Maybe(vk.DebugUtilsMessengerEXT),
	allocator:                vma.Allocator,
	graphics_queue:           vk.Queue,
	present_queue:            vk.Queue,
	surface:                  vk.SurfaceKHR,
	command_pool:             vk.CommandPool,
	descriptor_pool:          vk.DescriptorPool,
}

Graphics_Limits :: struct {
	max_sample_count:       Sample_Count_Flag,
	max_sampler_anisotropy: f32,
}

Graphics_Attachment_Flags :: distinct bit_set[Graphics_Attachment_Flag]
Graphics_Attachment_Flag :: enum {
	Depth,
	Stencil,
}

Graphics_Init_Info :: struct {
	swapchain_sample_count: Sample_Count_Flag,
	attachments:            Graphics_Attachment_Flags,
}

Swapchain_Configuration :: struct {
	present_mode:         vk.PresentModeKHR,
	depth_format:         vk.Format,
	depth_stencil_format: vk.Format,
	vk_surface_format:    vk.SurfaceFormatKHR,
}

Graphics :: struct {
	initialized:               bool,
	window:                    ^glfw.WindowHandle,
	vk_state:                  Vulkan_State,
	limits:                    Graphics_Limits,
	swapchain_cfg:             Swapchain_Configuration,
	swapchain:                 ^Swapchain,
	// managers
	buffer_manager:            ^Buffer_Manager,
	pipeline_manager:          ^Pipeline_Manager,
	surface_manager:           ^Surface_Manager,
	g_res_manager:             ^Global_Resource_Manager,
	descriptor_layout_manager: Descriptor_Layout_Manager,
	temp_material_pool:        ^Temp_Material_Pool, // TODO: move to Temps struct
	temp_transform_pool:       ^Temp_Transform_Pool,
	bindless:                  ^Bindless,
	cmd:                       vk.CommandBuffer,
	image_available_semaphore: vk.Semaphore,
	fence:                     vk.Fence,
	swapchain_resized:         bool,
	render_started:            bool,
	deffered_destructor:       ^Deferred_Destructor,
	buildin:                   ^Buildin_Resource,
}

Buffer_Usage_Flags :: distinct bit_set[Buffer_Usage_Flag]
Buffer_Usage_Flag :: enum {
	// GPU
	Vertex,
	Index,
	Uniform,
	Storage,
	Transfer,
	// CPU
	Host_Read,
	Host_Write,
}

Buffer :: struct {
	buffer:     vk.Buffer,
	vk_usage:   vk.BufferUsageFlags,
	usage:      Buffer_Usage_Flags,
	mapped:     rawptr,
	size:       Device_Size,
	alloc:      vma.Allocation,
	alloc_info: vma.AllocationInfo,
}

Uniform_Buffer_Handle :: distinct hm.Handle
Nil_Uniform_Buffer_Handle :: Uniform_Buffer_Handle{max(u32), max(u32)}
Storage_Buffer_Handle :: distinct hm.Handle
Nil_Storage_Buffer_Handle :: Storage_Buffer_Handle{max(u32), max(u32)}
Material_Handle :: distinct hm.Handle
Nil_Material_Buffer_Handle :: Material_Handle{max(u32), max(u32)}

Buffer_Manager :: struct {
	uniform_buffers: hm.Handle_Map(Uniform_Buffer, Uniform_Buffer_Handle),
	storage_buffers: hm.Handle_Map(Storage_Buffer, Storage_Buffer_Handle),
	materials:       hm.Handle_Map(Material, Material_Handle),
}

Resource :: union {
	Buffer,
	Texture,
	Buffer_Handle,
	Texture_Handle,
}

Resource_Handle :: union {
	Buffer_Handle,
	Texture_Handle,
}

Deferred_Destructor :: struct {
	resources:  [DEFERRED_DESTRUCTOR_SIZE]Resource,
	next_index: int,
}

@(private)
Single_Command :: struct {
	cmd: vk.CommandBuffer,
}

// SWAP CHAIN

Swapchain :: struct {
	swapchain:                  vk.SwapchainKHR,
	color_format:               vk.SurfaceFormatKHR,
	extent:                     vk.Extent2D,
	sample_count:               Sample_Count_Flag,
	msaa_color_texture:         Maybe(Texture),
	depth_image:                Texture,
	image_index:                u32,
	images:                     []vk.Image,
	image_views:                []vk.ImageView,
	frame_buffers:              []vk.Framebuffer,
	render_finished_semaphores: []vk.Semaphore,
}

// FEATURES

Physical_Device_Features :: struct {
	dynamic_rendering_local_read: vk.PhysicalDeviceDynamicRenderingLocalReadFeatures,
	// ^
	// | pNext
	features13:                   vk.PhysicalDeviceVulkan13Features,
	// ^
	// | pNext
	features12:                   vk.PhysicalDeviceVulkan12Features,
	// ^
	// | pNext
	features:                     vk.PhysicalDeviceFeatures2,
}

// MODEL

Cached_Buffer :: struct {
	buffer_h: Buffer_Handle,
	dirty:    bool,
	apply:    proc(data: ^Cached_Buffer, loc := #caller_location),
	data:     rawptr,
	type:     typeid,
}

Uniform_Buffer :: Cached_Buffer
Storage_Buffer :: Cached_Buffer
Material :: struct {
	pipeline_h: Render_Pipeline_Handle,
	using base: Cached_Buffer,
}

@(material)
Base_Material :: struct {
	color:   vec4,
	texture: Texture_Handle,
}

Gfx_Transform :: struct {
	using base: Transform,
}

// FRAME

Frame_Status :: enum {
	Success,
	IncorrectSwapchainSize,
}

Surface_Info_Type :: enum {
	None,
	Swapchain,
	Surface,
}

Surface_Info :: struct {
	type:                     Surface_Info_Type,
	sample_count:             Sample_Count_Flag,
	depth_format:             vk.Format,
	color_formats:            sm.Small_Array(MAX_COLOR_ATTACHMENTS, vk.Format),
	active_color_attachments: sm.Small_Array(MAX_COLOR_ATTACHMENTS, int), // FIX:
	width:                    u32,
	height:                   u32,
}

Frame_Data :: struct {
	cmd:          vk.CommandBuffer,
	status:       Frame_Status,
	surface_info: Surface_Info,
	camera:       Camera,
}

Render_Frame :: struct {
	state:       bool,
	image_index: u32,
}

Sync_Data :: struct {
	wait_semaphore_infos: []vk.SemaphoreSubmitInfo,
}

// BINDLESS

Texture_Handle :: distinct hm.Handle
Nil_Texture_Handle :: Texture_Handle{max(u32), max(u32)}
Buffer_Handle :: distinct hm.Handle
Nil_Buffer_Handle :: Buffer_Handle{max(u32), max(u32)}

Bindless :: struct {
	set:        vk.DescriptorSet,
	set_layout: vk.DescriptorSetLayout,
	textures:   hm.Handle_Map(Texture, Texture_Handle),
	buffers:    hm.Handle_Map(Buffer, Buffer_Handle),
}

// TEMP RESOURCES

Temp_Material_Pool :: Temp_Pool(Material_Handle)
Temp_Transform_Pool :: Temp_Pool(Gfx_Transform)

Temp_Pool :: struct($T: typeid) {
	resources:          []T,
	next_free_resource: u32,
}

Global_Resource_Manager :: struct {
	slots:      [MAX_SLOT_COUNT]Resource_Handle,
	free_slots: [MAX_SLOT_COUNT]bool,
}


@(require_results)
get_screen_size :: proc() -> (width: u32, height: u32) {return ctx.gfx.swapchain.extent.width,
		ctx.gfx.swapchain.extent.height}
@(require_results)
get_screen_width :: proc() -> u32 {return ctx.gfx.swapchain.extent.width}
@(require_results)
get_screen_height :: proc() -> u32 {return ctx.gfx.swapchain.extent.height}
@(require_results)
get_screen_aspect :: proc() -> f32 {return cast(f32)get_screen_width() / cast(f32)get_screen_height()}
@(require_results)
get_device_width :: proc() -> u32 {
	width, _ := glfw.GetFramebufferSize(ctx.gfx.window^)
	return cast(u32)width
}
@(require_results)
get_device_height :: proc() -> u32 {
	_, height := glfw.GetFramebufferSize(ctx.gfx.window^)
	return cast(u32)height
}
@(require_results)
screen_resized :: proc() -> bool {
	return ctx.gfx.swapchain_resized
}

begin_render :: proc(loc := #caller_location) -> Frame_Data {
	assert_gfx_ctx(loc)
	assert(!ctx.gfx.render_started, "Call end_render() after begin_render()", loc)

	_update_buffers()

	defer ctx.gfx.render_started = true

	frame_data := Frame_Data {
		cmd    = ctx.gfx.cmd,
		status = .Success,
	}

	// Wait for previous frame
	must(vk.WaitForFences(ctx.gfx.vk_state.device, 1, &ctx.gfx.fence, true, max(u64)))

	images: u32 = cast(u32)len(ctx.gfx.swapchain.images)
	acquire_result := vk.AcquireNextImageKHR(
		device = ctx.gfx.vk_state.device,
		swapchain = ctx.gfx.swapchain.swapchain,
		timeout = max(u64),
		semaphore = ctx.gfx.image_available_semaphore,
		fence = {},
		pImageIndex = &ctx.gfx.swapchain.image_index,
	)

	#partial switch acquire_result {
	case .ERROR_OUT_OF_DATE_KHR:
		frame_data.status = .IncorrectSwapchainSize
		return {}
	case .SUCCESS, .SUBOPTIMAL_KHR:
	case:
		log.panicf("acquire next image failure: %v", acquire_result)
	}

	must(vk.ResetFences(ctx.gfx.vk_state.device, 1, &ctx.gfx.fence))
	must(vk.ResetCommandBuffer(frame_data.cmd, {}))

	begin_info := vk.CommandBufferBeginInfo {
		sType = .COMMAND_BUFFER_BEGIN_INFO,
	}
	must(vk.BeginCommandBuffer(frame_data.cmd, &begin_info))

	return frame_data
}

end_render :: proc(frame_data: Frame_Data, sync_data: Sync_Data = {}) {
	if !ctx.gfx.render_started {
		log.error("Call begin_render() before end_render()")
	}
	defer ctx.gfx.render_started = false

	frame_data := frame_data

	must(vk.EndCommandBuffer(frame_data.cmd))

	wait_semaphore_infos := merge(
		sync_data.wait_semaphore_infos,
		[]vk.SemaphoreSubmitInfo {
			{
				sType = .SEMAPHORE_SUBMIT_INFO,
				semaphore = ctx.gfx.image_available_semaphore,
				stageMask = {.COLOR_ATTACHMENT_OUTPUT},
				deviceIndex = 0,
			},
		},
		context.temp_allocator,
	)

	comand_buffer_info := vk.CommandBufferSubmitInfo {
		sType         = .COMMAND_BUFFER_SUBMIT_INFO,
		commandBuffer = frame_data.cmd,
	}

	signal_semaphore_info := vk.SemaphoreSubmitInfo {
		sType     = .SEMAPHORE_SUBMIT_INFO,
		semaphore = ctx.gfx.swapchain.render_finished_semaphores[ctx.gfx.swapchain.image_index],
	}

	submit_info := vk.SubmitInfo2 {
		sType                    = .SUBMIT_INFO_2,
		waitSemaphoreInfoCount   = cast(u32)len(wait_semaphore_infos),
		pWaitSemaphoreInfos      = raw_data(wait_semaphore_infos),
		commandBufferInfoCount   = 1,
		pCommandBufferInfos      = &comand_buffer_info,
		signalSemaphoreInfoCount = 1,
		pSignalSemaphoreInfos    = &signal_semaphore_info,
	}
	must(vk.QueueSubmit2(ctx.gfx.vk_state.graphics_queue, 1, &submit_info, ctx.gfx.fence))

	present_info := vk.PresentInfoKHR {
		sType              = .PRESENT_INFO_KHR,
		waitSemaphoreCount = 1,
		pWaitSemaphores    = &ctx.gfx.swapchain.render_finished_semaphores[ctx.gfx.swapchain.image_index],
		swapchainCount     = 1,
		pSwapchains        = &ctx.gfx.swapchain.swapchain,
		pImageIndices      = &ctx.gfx.swapchain.image_index,
	}
	present_result := vk.QueuePresentKHR(ctx.gfx.vk_state.present_queue, &present_info)

	switch {
	case present_result == .ERROR_OUT_OF_DATE_KHR || present_result == .SUBOPTIMAL_KHR:
		frame_data.status = .IncorrectSwapchainSize
	case present_result == .SUCCESS:
	case:
		log.panicf("vulkan: present failure: %v", present_result)
	}

	if ctx.gfx.swapchain_resized {
		ctx.gfx.swapchain_resized = false
	}

	if frame_data.status == .IncorrectSwapchainSize {
		ctx.gfx.swapchain_resized = true
		_on_screen_resized()
	}

	_clear_temp_pool()
	_clear_deffered_destructor()
}

begin_draw :: proc(frame: Frame_Data, clear_color: vec4 = {0.0, 0.0, 0.0, 1.0}) -> Frame_Data {
	_transition_image_layout(
		frame.cmd,
		ctx.gfx.swapchain.images[ctx.gfx.swapchain.image_index],
		{.COLOR},
		ctx.gfx.swapchain.color_format.format,
		.UNDEFINED,
		.COLOR_ATTACHMENT_OPTIMAL,
		1,
	)

	color_attachment_info := _swapchaint_get_color_attachment_info(clear_color)

	depth_stencil_clear_value := vk.ClearValue {
		depthStencil = {1, 0},
	}

	depth_stencil_attachment_info := vk.RenderingAttachmentInfo {
		sType       = .RENDERING_ATTACHMENT_INFO,
		pNext       = nil,
		imageView   = ctx.gfx.swapchain.depth_image.view,
		imageLayout = .DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
		loadOp      = .CLEAR,
		storeOp     = .DONT_CARE,
		clearValue  = depth_stencil_clear_value,
	}

	rendering_info := vk.RenderingInfo {
		sType = .RENDERING_INFO,
		renderArea = {extent = ctx.gfx.swapchain.extent},
		layerCount = 1,
		colorAttachmentCount = 1,
		pColorAttachments = &color_attachment_info,
		pDepthAttachment = &depth_stencil_attachment_info,
		pStencilAttachment = &depth_stencil_attachment_info if _has_stencil_component(ctx.gfx.swapchain.depth_image.format) else nil,
	}

	vk.CmdBeginRendering(frame.cmd, &rendering_info)

	frame := frame

	frame.surface_info = Surface_Info {
		type         = .Swapchain,
		sample_count = ctx.gfx.swapchain.sample_count,
		depth_format = ctx.gfx.swapchain.depth_image.format,
		width        = ctx.gfx.swapchain.extent.width,
		height       = ctx.gfx.swapchain.extent.height,
	}
	sm.push(&frame.surface_info.color_formats, ctx.gfx.swapchain.color_format.format)

	cmd_set_full_viewport_scissor(frame)

	return frame
}

end_draw :: proc(frame: Frame_Data) {
	vk.CmdEndRendering(frame.cmd)

	_transition_image_layout(
		frame.cmd,
		ctx.gfx.swapchain.images[ctx.gfx.swapchain.image_index],
		{.COLOR},
		ctx.gfx.swapchain.color_format.format,
		.COLOR_ATTACHMENT_OPTIMAL,
		.PRESENT_SRC_KHR,
		1,
	)
}

@(private)
_on_screen_resized :: proc() {
	// Don't do anything when minimized.
	for w, h := glfw.GetFramebufferSize(ctx.gfx.window^);
	    w == 0 || h == 0;
	    w, h = glfw.GetFramebufferSize(ctx.gfx.window^) {
		glfw.WaitEvents()

		// Handle closing while minimized.
		if glfw.WindowShouldClose(ctx.gfx.window^) {return}
	}
	_recreate_swapchain()
	_surface_manager_resize_fit_screen_surfaces(ctx.gfx.surface_manager)
}

wait_render_completion :: proc() {
	vk.DeviceWaitIdle(ctx.gfx.vk_state.device)
}

//  ██████╗███╗   ███╗██████╗ 
// ██╔════╝████╗ ████║██╔══██╗
// ██║     ██╔████╔██║██║  ██║
// ██║     ██║╚██╔╝██║██║  ██║
// ╚██████╗██║ ╚═╝ ██║██████╔╝
//  ╚═════╝╚═╝     ╚═╝╚═════╝ 

cmd_set_full_viewport_scissor :: proc(frame_data: Frame_Data, loc := #caller_location) {
	assert_gfx_ctx(loc)
	width := get_screen_width()
	height := get_screen_height()

	cmd_set_viewport(frame_data, width, height, loc = loc)
	cmd_set_scissor(frame_data, width, height, loc = loc)
}

cmd_set_viewport :: proc(frame_data: Frame_Data, width, height: u32, max_depth: f32 = 1, loc := #caller_location) {
	assert_gfx_ctx(loc)

	viewport := vk.Viewport {
		width    = cast(f32)width,
		height   = cast(f32)height,
		maxDepth = 1,
	}
	vk.CmdSetViewport(frame_data.cmd, 0, 1, &viewport)
}

cmd_set_scissor :: proc(frame_data: Frame_Data, width, height: u32, offset: ivec2 = 0, loc := #caller_location) {
	assert_gfx_ctx(loc)

	scissor := vk.Rect2D {
		extent = {width = width, height = height},
		offset = {x = offset.x, y = offset.y},
	}
	vk.CmdSetScissor(frame_data.cmd, 0, 1, &scissor)
}

cmd_bind_vertex_buffer :: proc(
	frame_data: Frame_Data,
	buffer: Buffer,
	binding: u32,
	offset := vk.DeviceSize{},
	loc := #caller_location,
) {
	assert(.VERTEX_BUFFER in buffer.vk_usage, loc = loc)

	offset := offset
	buffer := buffer

	vk.CmdBindVertexBuffers(frame_data.cmd, binding, 1, &buffer.buffer, &offset)
}

cmd_bind_index_buffer :: proc(
	frame_data: Frame_Data,
	buffer: Buffer,
	offset := vk.DeviceSize{},
	index_type := vk.IndexType.UINT16,
	loc := #caller_location,
) {
	assert(.INDEX_BUFFER in buffer.vk_usage, loc = loc)

	offset := offset
	buffer := buffer

	vk.CmdBindIndexBuffer(frame_data.cmd, buffer.buffer, offset, index_type)
}

cmd_push_constants :: proc(
	cmd: Command_Buffer,
	pipeline: Pipeline,
	const: ^$T,
	stages := vk.ShaderStageFlags_ALL_GRAPHICS,
) {
	layout := get_pipeline_layout(pipeline.layout)
	vk.CmdPushConstants(cmd, layout, stages, 0, size_of(const^), const)
}

cmd_draw :: proc(frame_data: Frame_Data, vertex_count: u32, instance_count: u32 = 1, loc := #caller_location) {
	assert_frame_data(frame_data, loc)
	vk.CmdDraw(frame_data.cmd, vertex_count, instance_count, 0, 0)
}

cmd_draw_indexed :: proc(frame_data: Frame_Data, vertex_count: u32, instance_count: u32 = 1, loc := #caller_location) {
	assert_frame_data(frame_data, loc)
	vk.CmdDrawIndexed(frame_data.cmd, vertex_count, instance_count, 0, 0, 0)
}

cmd_bind_material :: proc(frame_data: Frame_Data, m: ^Material, loc := #caller_location) -> ^Graphics_Pipeline {
	pipeline, ok := get_render_pipeline(m.pipeline_h)
	return cmd_bind_render_pipeline(frame_data, pipeline, loc)
}

cmd_bind_render_pipeline :: proc(
	frame_data: Frame_Data,
	pipeline: ^Render_Pipeline,
	loc := #caller_location,
) -> ^Graphics_Pipeline {
	assert_frame_data(frame_data, loc)

	graphics_pipeline := render_pipeline_get_pipeline(pipeline, frame_data.surface_info, loc)
	vk.CmdBindPipeline(frame_data.cmd, .GRAPHICS, graphics_pipeline.pipeline)
	cmd_bind_descriptor_set_graphics(frame_data, graphics_pipeline, get_descriptor_set_bindless())

	return graphics_pipeline
}

cmd_bind_compute_pipeline :: proc(pipeline: Compute_Pipeline, frame_data: Frame_Data, loc := #caller_location) {
	assert_frame_data(frame_data, loc)

	vk.CmdBindPipeline(frame_data.cmd, .COMPUTE, pipeline.pipeline)
}

cmd_bind_descriptor_set_graphics :: proc(
	frame_data: Frame_Data,
	pipeline: ^Pipeline,
	descriptor_sets: ..vk.DescriptorSet,
	loc := #caller_location,
) {
	_cmd_bind_descriptor_set(frame_data, .GRAPHICS, pipeline, descriptor_sets, loc)
}

cmd_bind_descriptor_set_compute :: proc(
	frame_data: Frame_Data,
	pipeline: ^Pipeline,
	descriptor_sets: ..vk.DescriptorSet,
	loc := #caller_location,
) {
	_cmd_bind_descriptor_set(frame_data, .COMPUTE, pipeline, descriptor_sets, loc)
}

@(private = "file")
_cmd_bind_descriptor_set :: proc(
	frame_data: Frame_Data,
	bind_point: vk.PipelineBindPoint,
	pipeline: ^Pipeline,
	descriptor_sets: []vk.DescriptorSet,
	loc := #caller_location,
) {
	assert_gfx_ctx(loc)

	layout := get_pipeline_layout(pipeline.layout)

	vk.CmdBindDescriptorSets(
		frame_data.cmd,
		bind_point,
		layout,
		0,
		cast(u32)len(descriptor_sets),
		raw_data(descriptor_sets),
		0,
		nil,
	)
}

@(require_results)
begin_single_cmd :: proc() -> Single_Command {
	alloc_info := vk.CommandBufferAllocateInfo {
		sType              = .COMMAND_BUFFER_ALLOCATE_INFO,
		level              = .PRIMARY,
		commandPool        = ctx.gfx.vk_state.command_pool,
		commandBufferCount = 1,
	}

	command_buffer: vk.CommandBuffer
	must(vk.AllocateCommandBuffers(ctx.gfx.vk_state.device, &alloc_info, &command_buffer))

	begin_info := vk.CommandBufferBeginInfo {
		sType = .COMMAND_BUFFER_BEGIN_INFO,
		flags = {.ONE_TIME_SUBMIT},
	}
	must(vk.BeginCommandBuffer(command_buffer, &begin_info))

	return Single_Command{cmd = command_buffer}
}

end_single_cmd :: proc(single_command: Single_Command) {
	command_buffer := single_command.cmd

	must(vk.EndCommandBuffer(command_buffer))

	submit_info := vk.SubmitInfo {
		sType              = .SUBMIT_INFO,
		commandBufferCount = 1,
		pCommandBuffers    = &command_buffer,
	}

	must(vk.QueueSubmit(ctx.gfx.vk_state.graphics_queue, 1, &submit_info, 0))
	must(vk.QueueWaitIdle(ctx.gfx.vk_state.graphics_queue))

	vk.FreeCommandBuffers(ctx.gfx.vk_state.device, ctx.gfx.vk_state.command_pool, 1, &command_buffer)
}

@(private)
_cmd_buffer_barrier :: proc(
	cmd: vk.CommandBuffer,
	vk_buffer: vk.Buffer,
	src_access_mask: vk.AccessFlags,
	dst_access_mask: vk.AccessFlags,
	src_stage_mask: vk.PipelineStageFlags,
	dst_stage_mask: vk.PipelineStageFlags,
) {
	buffer_barrier := vk.BufferMemoryBarrier {
		sType               = .BUFFER_MEMORY_BARRIER,
		srcAccessMask       = src_access_mask,
		dstAccessMask       = dst_access_mask,
		srcQueueFamilyIndex = vk.QUEUE_FAMILY_IGNORED,
		dstQueueFamilyIndex = vk.QUEUE_FAMILY_IGNORED,
		buffer              = vk_buffer,
		offset              = 0,
		size                = cast(vk.DeviceSize)vk.WHOLE_SIZE,
	}
	vk.CmdPipelineBarrier(cmd, src_stage_mask, dst_stage_mask, {}, 0, nil, 1, &buffer_barrier, 0, nil)
}

// ███╗   ███╗ █████╗ ████████╗███████╗██████╗ ██╗ █████╗ ██╗     
// ████╗ ████║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██║██╔══██╗██║     
// ██╔████╔██║███████║   ██║   █████╗  ██████╔╝██║███████║██║     
// ██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  ██╔══██╗██║██╔══██║██║     
// ██║ ╚═╝ ██║██║  ██║   ██║   ███████╗██║  ██║██║██║  ██║███████╗
// ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚══════╝

Empty_Material :: Material


create_mtrl_empty :: proc(pipeline_h: Render_Pipeline_Handle) -> Material_Handle {
	m := Material {
		pipeline_h = pipeline_h,
	}
	m.pipeline_h = pipeline_h
	m.type = typeid_of(^Empty_Material)
	m.dirty = false

	return store_material(m)
}

store_material :: proc(m: Material) -> Material_Handle {
	return hm.insert(&ctx.gfx.buffer_manager.materials, m)
}

get_material :: proc(handle: Material_Handle) -> (^Material, bool) {
	return hm.get(&ctx.gfx.buffer_manager.materials, handle)
}

detstroy_material :: proc(handle: Material_Handle) -> bool {
	material, ok := hm.remove(&ctx.gfx.buffer_manager.materials, handle)
	_destroy_mtrl(&material)
	return ok
}

mtrl_set_pipeline :: proc(material: ^Material, pipeline_h: Render_Pipeline_Handle, loc := #caller_location) {
	assert_not_nil(material, loc)
	material.pipeline_h = pipeline_h
}

@(private)
_destroy_mtrl :: proc(material: ^Material, loc := #caller_location) {
	assert_gfx_ctx(loc)
	assert_not_nil(material, loc)
	free(material.data)

	destroy_buffer_h(material.buffer_h, loc)
}

// ███████╗██╗    ██╗ █████╗ ██████╗      ██████╗██╗  ██╗ █████╗ ██╗███╗   ██╗
// ██╔════╝██║    ██║██╔══██╗██╔══██╗    ██╔════╝██║  ██║██╔══██╗██║████╗  ██║
// ███████╗██║ █╗ ██║███████║██████╔╝    ██║     ███████║███████║██║██╔██╗ ██║
// ╚════██║██║███╗██║██╔══██║██╔═══╝     ██║     ██╔══██║██╔══██║██║██║╚██╗██║
// ███████║╚███╔███╔╝██║  ██║██║         ╚██████╗██║  ██║██║  ██║██║██║ ╚████║
// ╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝          ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝

@(private)
_init_swapchain :: proc(sample_count: Sample_Count_Flag) {
	ctx.gfx.swapchain = _swapchain_new(sample_count)
	sc := begin_single_cmd()
	_swapchain_setup(ctx.gfx.swapchain, sc.cmd)
	end_single_cmd(sc)
}

@(private)
_destroy_swapchain :: proc() {
	_swapchain_destroy(ctx.gfx.swapchain)
}

@(private)
_recreate_swapchain :: proc() {
	_swapchain_recreate(ctx.gfx.swapchain)
}

@(private)
_swapchaint_get_color_attachment_info :: proc(clear_color: vec4) -> vk.RenderingAttachmentInfo {
	vk_clear_color := vk.ClearValue {
		color = {float32 = clear_color},
	}

	color_attachment_info := vk.RenderingAttachmentInfo {
		sType              = .RENDERING_ATTACHMENT_INFO,
		pNext              = nil,
		imageLayout        = .ATTACHMENT_OPTIMAL,
		resolveImageLayout = .COLOR_ATTACHMENT_OPTIMAL,
		loadOp             = .CLEAR,
		storeOp            = .STORE,
		clearValue         = vk_clear_color,
	}

	msaa_color_texture, has_msaa_color := ctx.gfx.swapchain.msaa_color_texture.?

	if has_msaa_color {
		color_attachment_info.imageView = msaa_color_texture.view
		color_attachment_info.resolveImageView = ctx.gfx.swapchain.image_views[ctx.gfx.swapchain.image_index]
		color_attachment_info.resolveMode = {.AVERAGE_KHR}
	} else {
		color_attachment_info.imageView = ctx.gfx.swapchain.image_views[ctx.gfx.swapchain.image_index]}

	return color_attachment_info
}

@(private = "file")
@(require_results)
_swapchain_new :: proc(sample_count: Sample_Count_Flag) -> ^Swapchain {
	indices := _find_queue_families(ctx.gfx.vk_state.physical_device, ctx.gfx.vk_state.surface)

	surface_format := ctx.gfx.swapchain_cfg.vk_surface_format
	present_mode := ctx.gfx.swapchain_cfg.present_mode
	capabilities := _get_swapchaint_capabilites()
	extent := _choose_swapchain_extent(ctx.gfx.window, capabilities)

	image_count := capabilities.minImageCount + 1
	if capabilities.maxImageCount > 0 && image_count > capabilities.maxImageCount {
		image_count = capabilities.maxImageCount
	}

	create_info := vk.SwapchainCreateInfoKHR {
		sType            = .SWAPCHAIN_CREATE_INFO_KHR,
		surface          = ctx.gfx.vk_state.surface,
		minImageCount    = image_count,
		imageFormat      = surface_format.format,
		imageColorSpace  = surface_format.colorSpace,
		imageExtent      = extent,
		imageArrayLayers = 1,
		imageUsage       = {.COLOR_ATTACHMENT},
		preTransform     = capabilities.currentTransform,
		compositeAlpha   = {.OPAQUE},
		presentMode      = present_mode,
		clipped          = true,
	}

	if indices.graphics != indices.present {
		create_info.imageSharingMode = .CONCURRENT
		create_info.queueFamilyIndexCount = 2
		create_info.pQueueFamilyIndices = raw_data([]u32{indices.graphics.?, indices.present.?})
	}

	vk_swapchain: vk.SwapchainKHR
	must(vk.CreateSwapchainKHR(ctx.gfx.vk_state.device, &create_info, nil, &vk_swapchain))

	swapchain := new(Swapchain)
	swapchain.swapchain = vk_swapchain
	swapchain.color_format = surface_format
	swapchain.extent = extent
	swapchain.sample_count = sample_count
	_swapchain_setup_images(swapchain)
	_swapchain_setup_semaphores(swapchain)

	return swapchain
}

@(private = "file")
_swapchain_setup :: proc(swapchain: ^Swapchain, command_buffer: vk.CommandBuffer) {
	if swapchain.sample_count != ._1 {
		_swapchain_setup_msaa_color_texture(swapchain)
	}

	if .Depth in ctx.info.gfx.attachments {
		stencil := .Stencil in ctx.info.gfx.attachments
		_swapchain_setupt_depth_texture(swapchain, command_buffer, stencil)
	}
}

@(private = "file")
_swapchain_recreate :: proc(swapchain: ^Swapchain) {
	vk.DeviceWaitIdle(ctx.gfx.vk_state.device)

	_swapchain_destroy(swapchain)

	swapchain := _swapchain_new(swapchain.sample_count)

	sc := begin_single_cmd()
	_swapchain_setup(swapchain, sc.cmd)
	end_single_cmd(sc)
}

@(private = "file")
_swapchain_destroy :: proc(swapchain: ^Swapchain) {
	msaa_color_texture, has_color_texture := swapchain.msaa_color_texture.?
	if has_color_texture {
		destroy_texture(&msaa_color_texture)
	}

	if .Depth in ctx.info.gfx.attachments {
		destroy_texture(&swapchain.depth_image)
	}

	for sem in swapchain.render_finished_semaphores {
		vk.DestroySemaphore(ctx.gfx.vk_state.device, sem, nil)
	}
	delete(swapchain.render_finished_semaphores)

	for view in swapchain.image_views {
		vk.DestroyImageView(ctx.gfx.vk_state.device, view, nil)
	}

	delete(swapchain.image_views)
	delete(swapchain.images)

	vk.DestroySwapchainKHR(ctx.gfx.vk_state.device, swapchain.swapchain, nil)

	free(swapchain)
}

@(private)
_get_swapchaint_capabilites :: proc() -> (capabilities: vk.SurfaceCapabilitiesKHR) {
	device, vk_surface := ctx.gfx.vk_state.physical_device, ctx.gfx.vk_state.surface
	must(vk.GetPhysicalDeviceSurfaceCapabilitiesKHR(device, vk_surface, &capabilities))

	return
}

@(private = "file")
_swapchain_setup_msaa_color_texture :: proc(swapchain: ^Swapchain) {
	color_format := swapchain.color_format.format

	image, allocation, allocation_info := _create_image(
		swapchain.extent.width,
		swapchain.extent.height,
		1,
		swapchain.sample_count,
		color_format,
		vk.ImageTiling.OPTIMAL,
		vk.ImageUsageFlags{.TRANSIENT_ATTACHMENT, .COLOR_ATTACHMENT},
		vma.MemoryUsage.AUTO_PREFER_DEVICE,
		vma.AllocationCreateFlags{},
	)

	view := _create_image_view(image, color_format, {.COLOR}, 1)

	texture := Texture {
		name            = "swapchain_msaa_color_texture",
		image           = image,
		format          = color_format,
		view            = view,
		allocation      = allocation,
		allocation_info = allocation_info,
	}

	swapchain.msaa_color_texture = texture

	s := begin_single_cmd()
	_transition_image_layout(
		s.cmd,
		texture.image,
		{.COLOR},
		ctx.gfx.swapchain.color_format.format,
		.UNDEFINED,
		.COLOR_ATTACHMENT_OPTIMAL,
		1,
	)
	end_single_cmd(s)
}

@(private = "file")
_swapchain_setupt_depth_texture :: proc(swapchain: ^Swapchain, command_buffer: vk.CommandBuffer, stencil: bool) {
	assert(.Depth in ctx.info.gfx.attachments)

	format: vk.Format
	if stencil {
		format = ctx.gfx.swapchain_cfg.depth_stencil_format
	} else {
		format = ctx.gfx.swapchain_cfg.depth_format
	}

	image, allocation, allocation_info := _create_image(
		swapchain.extent.width,
		swapchain.extent.height,
		1,
		swapchain.sample_count,
		format,
		vk.ImageTiling.OPTIMAL,
		vk.ImageUsageFlags{.DEPTH_STENCIL_ATTACHMENT},
		vma.MemoryUsage.AUTO_PREFER_DEVICE,
		vma.AllocationCreateFlags{},
	)

	aspect: vk.ImageAspectFlags = {.DEPTH, .STENCIL} if stencil else {.DEPTH}
	_transition_image_layout(command_buffer, image, aspect, format, .UNDEFINED, .DEPTH_STENCIL_ATTACHMENT_OPTIMAL, 1)

	view := _create_image_view(image, format, aspect, 1)
	swapchain.depth_image = Texture {
		image           = image,
		format          = format,
		view            = view,
		allocation      = allocation,
		allocation_info = allocation_info,
	}
}

@(private = "file")
_swapchain_setup_images :: proc(swapchain: ^Swapchain) {
	swapchain.image_index = 0

	count: u32
	must(vk.GetSwapchainImagesKHR(ctx.gfx.vk_state.device, swapchain.swapchain, &count, nil))

	swapchain.images = make([]vk.Image, count)
	swapchain.image_views = make([]vk.ImageView, count)
	must(vk.GetSwapchainImagesKHR(ctx.gfx.vk_state.device, swapchain.swapchain, &count, raw_data(swapchain.images)))

	for image, i in swapchain.images {
		swapchain.image_views[i] = _create_image_view(image, swapchain.color_format.format, {.COLOR}, 1)
	}
}

@(private = "file")
_swapchain_setup_semaphores :: proc(swapchain: ^Swapchain) {
	swapchain.render_finished_semaphores = make([]vk.Semaphore, len(swapchain.images))
	sem_info := vk.SemaphoreCreateInfo {
		sType = .SEMAPHORE_CREATE_INFO,
	}
	for _, i in swapchain.images {
		must(vk.CreateSemaphore(ctx.gfx.vk_state.device, &sem_info, nil, &swapchain.render_finished_semaphores[i]))
	}
}

@(private = "file")
@(require_results)
_choose_swapchain_extent :: proc(window: ^glfw.WindowHandle, capabilities: vk.SurfaceCapabilitiesKHR) -> vk.Extent2D {
	// special value (0xFFFFFFFF, 0xFFFFFFFF) indicating that the surface size will be determined
	// by the extent of a swapchain targeting the surface.
	if capabilities.currentExtent.width != max(u32) {
		return capabilities.currentExtent
	}

	width, height := glfw.GetFramebufferSize(window^)
	return vk.Extent2D {
		width = clamp(u32(width), capabilities.minImageExtent.width, capabilities.maxImageExtent.width),
		height = clamp(u32(height), capabilities.minImageExtent.height, capabilities.maxImageExtent.height),
	}
}

// ██████╗ ██╗   ██╗███████╗███████╗███████╗██████╗
// ██╔══██╗██║   ██║██╔════╝██╔════╝██╔════╝██╔══██╗
// ██████╔╝██║   ██║█████╗  █████╗  █████╗  ██████╔╝
// ██╔══██╗██║   ██║██╔══╝  ██╔══╝  ██╔══╝  ██╔══██╗
// ██████╔╝╚██████╔╝██║     ██║     ███████╗██║  ██║
// ╚═════╝  ╚═════╝ ╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝

@(require_results)
create_buffer :: proc(
	usage: Buffer_Usage_Flags,
	size: Device_Size,
	data: rawptr = nil,
	loc := #caller_location,
) -> Buffer {
	when GFX_DEBUG {
		assert(size > 0, loc = loc)
		required_flags := [?]Buffer_Usage_Flag{.Vertex, .Index, .Uniform, .Storage, .Transfer}
		has_gpu_usage := false
		for flag in required_flags {
			if flag in usage {
				has_gpu_usage = true
				break
			}
		}
		assert(
			has_gpu_usage == true,
			fmt.tprintf("Buffer should have some of these usage flags %v", required_flags),
			loc,
		)
	}

	vk_usage, dst_access_mask, dst_stage_mask := _buffer_get_usage_and_dst_access_stage_mask(usage)

	memory_usage: vma.MemoryUsage
	memory_flags: vma.AllocationCreateFlags

	if .Host_Write in usage {
		memory_usage = .CPU_ONLY
		memory_usage = .AUTO_PREFER_HOST
		memory_flags += {.MAPPED, .HOST_ACCESS_SEQUENTIAL_WRITE}
	}
	if .Host_Read in usage {
		memory_usage = .CPU_ONLY
		memory_usage = .AUTO_PREFER_HOST
		memory_flags -= {.MAPPED, .HOST_ACCESS_SEQUENTIAL_WRITE}
		memory_flags += {.HOST_ACCESS_RANDOM}
	}

	vk_buffer: vk.Buffer
	alloc: vma.Allocation
	alloc_info: vma.AllocationInfo
	mapped: rawptr

	if (.Host_Write in usage || .Host_Read in usage) {
		vk_buffer, alloc, alloc_info = _vk_create_buffer(size, vk_usage, memory_usage, memory_flags, {}, {})
		_vk_map_memory(alloc, &mapped, loc)
		if data != nil {
			_vk_buffer_fill_mapped_memory(alloc, alloc_info, data, size, mapped)
		}
	} else {
		if data != nil {
			vk_buffer, alloc, alloc_info = _vk_create_device_local_buffer(
				data,
				size,
				vk_usage,
				dst_access_mask,
				dst_stage_mask,
				loc,
			)
		} else {
			vk_usage += {.TRANSFER_DST}
			memory_usage = .AUTO_PREFER_DEVICE
			vk_buffer, alloc, alloc_info = _vk_create_buffer(size, vk_usage, memory_usage, {})
		}
	}

	_vk_set_debug_object_name(
		vk_buffer,
		.BUFFER,
		fmt.tprintf("%v %s", usage, _location_to_string(loc, context.temp_allocator)),
	)

	return Buffer {
		buffer = vk_buffer,
		size = size,
		usage = usage,
		vk_usage = vk_usage,
		alloc = alloc,
		alloc_info = alloc_info,
	}
}

@(private)
_buffer_get_usage_and_dst_access_stage_mask :: proc(
	usage: Buffer_Usage_Flags,
) -> (
	vk_usage: vk.BufferUsageFlags,
	dst_access_mask: vk.AccessFlags,
	dst_stage_mask: vk.PipelineStageFlags,
) {
	if .Vertex in usage {
		vk_usage += {.VERTEX_BUFFER}
		dst_access_mask += {.SHADER_READ}
		dst_stage_mask += {.VERTEX_SHADER}
	}
	if .Index in usage {
		vk_usage += {.INDEX_BUFFER}
		dst_access_mask += {.INDEX_READ}
		dst_stage_mask += {.VERTEX_INPUT}
	}
	if .Uniform in usage {
		vk_usage += {.UNIFORM_BUFFER}
		dst_access_mask += {.UNIFORM_READ}
		dst_stage_mask += {.VERTEX_SHADER, .FRAGMENT_SHADER, .GEOMETRY_SHADER}
	}
	if .Storage in usage {
		vk_usage += {.STORAGE_BUFFER}
		dst_access_mask += {.SHADER_READ, .SHADER_WRITE}
		dst_stage_mask += {.COMPUTE_SHADER, .VERTEX_SHADER, .GEOMETRY_SHADER, .FRAGMENT_SHADER}
	}
	if .Transfer in usage {
		vk_usage += {.TRANSFER_SRC}
		dst_access_mask += {.TRANSFER_READ}
		dst_stage_mask += {.TRANSFER}
	}
	return
}

buffer_fill :: proc(b: ^Buffer, data: rawptr, size: Device_Size, offset: Device_Size = 0, loc := #caller_location) {
	assert(b != nil, loc = loc)
	assert(data != nil, loc = loc)
	assert(size > 0, loc = loc)
	mem_props := _get_memory_properties(b.alloc_info)

	if .HOST_VISIBLE in mem_props {
		if b.mapped == nil do _vk_map_memory(b.alloc, &b.mapped)
		_vk_buffer_fill_mapped_memory(b.alloc, b.alloc_info, data, size, b.mapped)
	} else if .TRANSFER_DST in b.vk_usage {
		sc := begin_single_cmd()
		staging_buffer := _create_staging_buffer(data, size)
		defer destroy_buffer(&staging_buffer, loc)
		_, dst_access_mask, dst_stage_mask := _buffer_get_usage_and_dst_access_stage_mask(b.usage)

		_cmd_buffer_barrier(sc.cmd, staging_buffer.buffer, {.HOST_WRITE}, {.TRANSFER_READ}, {.HOST}, {.TRANSFER})
		_cmd_copy_buffer(sc.cmd, staging_buffer.buffer, b.buffer, size)
		_cmd_buffer_barrier(sc.cmd, b.buffer, {.TRANSFER_WRITE}, dst_access_mask, {.TRANSFER}, dst_stage_mask)
		end_single_cmd(sc)
	} else {
		log.info(b.vk_usage)
		log.panic("Couldn't fill buffer", loc)
	}
}

_vk_buffer_fill_mapped_memory :: proc(
	alloc: vma.Allocation,
	allloc_info: vma.AllocationInfo,
	data: rawptr,
	size: Device_Size,
	mapped: rawptr,
) {
	assert(data != nil)
	assert(size > 0)
	assert(mapped != nil)
	mem_props := _get_memory_properties(allloc_info)
	mem.copy(mapped, data, int(size))
	if !(.HOST_COHERENT in mem_props) {
		vma.FlushAllocation(ctx.gfx.vk_state.allocator, alloc, 0, cast(vk.DeviceSize)vk.WHOLE_SIZE)
	}
}

@(private)
_get_memory_properties :: proc(alloc_info: vma.AllocationInfo) -> vk.MemoryPropertyFlags {
	return ctx.gfx.vk_state.memory_propertices.memoryTypes[alloc_info.memoryType].propertyFlags
}

buffer_read :: proc(b: ^Buffer, loc := #caller_location) -> (data: rawptr, size: Device_Size) {
	mem_props := _get_memory_properties(b.alloc_info)
	assert(.HOST_VISIBLE in mem_props, loc = loc)
	if b.mapped == nil {
		_vk_map_memory(b.alloc, &b.mapped, loc)
	}
	if !(.HOST_COHERENT in mem_props) {
		vma.InvalidateAllocation(ctx.gfx.vk_state.allocator, b.alloc, 0, cast(vk.DeviceSize)vk.WHOLE_SIZE)
	}
	return b.mapped, b.size
}

destroy_buffer :: proc(buffer: ^Buffer, loc := #caller_location) {
	assert_not_nil(buffer, loc)

	if (buffer.mapped != nil) {
		vma.UnmapMemory(ctx.gfx.vk_state.allocator, buffer.alloc)
		buffer.mapped = nil
	}
	vma.DestroyBuffer(ctx.gfx.vk_state.allocator, buffer.buffer, buffer.alloc)
}

@(private)
_cmd_copy_buffer :: proc(cmd: vk.CommandBuffer, src_buffer: vk.Buffer, dst_buffer: vk.Buffer, size: vk.DeviceSize) {
	copy := vk.BufferCopy {
		srcOffset = 0,
		dstOffset = 0,
		size      = size,
	}
	vk.CmdCopyBuffer(cmd, src_buffer, dst_buffer, 1, &copy)
}

@(private)
_vk_create_buffer :: proc(
	size: vk.DeviceSize,
	usage: vk.BufferUsageFlags,
	memory_usage: vma.MemoryUsage,
	memory_flags: vma.AllocationCreateFlags,
	required_flags: vk.MemoryPropertyFlags = {},
	preferred_flags: vk.MemoryPropertyFlags = {},
) -> (
	vk.Buffer,
	vma.Allocation,
	vma.AllocationInfo,
) {
	buffer_info := vk.BufferCreateInfo {
		sType       = .BUFFER_CREATE_INFO,
		size        = size,
		usage       = usage,
		sharingMode = .EXCLUSIVE,
	}

	allocation_create_info := vma.AllocationCreateInfo {
		usage          = memory_usage,
		flags          = memory_flags,
		requiredFlags  = required_flags,
		preferredFlags = preferred_flags,
	}

	vk_buffer: vk.Buffer
	allocation: vma.Allocation
	allocation_info: vma.AllocationInfo
	vma.CreateBuffer(
		ctx.gfx.vk_state.allocator,
		&buffer_info,
		&allocation_create_info,
		&vk_buffer,
		&allocation,
		&allocation_info,
	)

	return vk_buffer, allocation, allocation_info
}

@(private = "file")
_vk_create_device_local_buffer :: proc(
	data: rawptr,
	size: vk.DeviceSize,
	usage: vk.BufferUsageFlags,
	dst_access_mask: vk.AccessFlags,
	dst_stage_mask: vk.PipelineStageFlags,
	loc := #caller_location,
) -> (
	vk_buffer: vk.Buffer,
	allocation: vma.Allocation,
	allocation_info: vma.AllocationInfo,
) {
	sc := begin_single_cmd()

	// TODO: Don't create a staging buffer if the device has enough DEVICE_LOCAL and HOST_VISIBLE memeory
	// Staging buffer
	staging_buffer := _create_staging_buffer(data, size, loc)
	_cmd_buffer_barrier(sc.cmd, staging_buffer.buffer, {.HOST_WRITE}, {.TRANSFER_READ}, {.HOST}, {.TRANSFER})
	defer destroy_buffer(&staging_buffer)

	// Result buffer
	vk_buffer, allocation, allocation_info = _vk_create_buffer(size, {.TRANSFER_DST} + usage, .AUTO_PREFER_DEVICE, {})
	_cmd_copy_buffer(sc.cmd, staging_buffer.buffer, vk_buffer, size)
	_cmd_buffer_barrier(sc.cmd, vk_buffer, {.TRANSFER_WRITE}, dst_access_mask, {.TRANSFER}, dst_stage_mask)

	end_single_cmd(sc)
	return
}

_create_staging_buffer :: proc(data: rawptr, size: Device_Size, loc := #caller_location) -> (buffer: Buffer) {
	assert(data != nil, loc = loc)
	assert(size > 0, loc = loc)
	vk_buffer, alloc, alloc_info := _vk_create_buffer(
		size,
		{.TRANSFER_SRC},
		.AUTO_PREFER_HOST,
		{.HOST_ACCESS_RANDOM, .MAPPED},
		{},
		{},
	)
	_vk_map_memory(alloc, &buffer.mapped)
	_vk_buffer_fill_mapped_memory(alloc, alloc_info, data, size, buffer.mapped)

	return Buffer{buffer = vk_buffer, size = size, vk_usage = {.TRANSFER_SRC}, alloc = alloc, alloc_info = alloc_info}
}

@(private)
_vk_map_memory :: proc(alloc: vma.Allocation, out_mapped: ^rawptr, loc := #caller_location) {
	must(vma.MapMemory(ctx.gfx.vk_state.allocator, alloc, out_mapped), loc = loc)
}

@(private)
_init_buffer_manager :: proc() {
	ctx.gfx.buffer_manager = new(Buffer_Manager)
}

@(private)
_destroy_buffer_manager :: proc() {
	for ubo in ctx.gfx.buffer_manager.uniform_buffers.values {
		free(ubo.data)
	}
	hm.destroy(&ctx.gfx.buffer_manager.uniform_buffers)

	for sbo in ctx.gfx.buffer_manager.storage_buffers.values {
		free(sbo.data)
	}
	hm.destroy(&ctx.gfx.buffer_manager.storage_buffers)

	for mtrl in ctx.gfx.buffer_manager.materials.values {
		free(mtrl.data)
	}
	hm.destroy(&ctx.gfx.buffer_manager.materials)

	free(ctx.gfx.buffer_manager)
}

@(private)
_update_buffers :: proc() {
	// Materials
	for &m in ctx.gfx.buffer_manager.materials.values {
		if m.dirty {
			m.apply(&m)
		}
	}

	// Uniform buffers
	for &ubo in ctx.gfx.buffer_manager.uniform_buffers.values {
		if ubo.dirty {
			ubo.apply(&ubo)
		}
	}

	// Storage buffers
	for &sbo in ctx.gfx.buffer_manager.storage_buffers.values {
		if sbo.dirty {
			sbo.apply(&sbo)
		}
	}
}

// ▄▄ ▄▄ ▄▄  ▄▄ ▄▄ ▄▄▄▄▄  ▄▄▄  ▄▄▄▄  ▄▄   ▄▄   ▄▄▄▄  ▄▄ ▄▄ ▄▄▄▄▄ ▄▄▄▄▄ ▄▄▄▄▄ ▄▄▄▄
// ██ ██ ███▄██ ██ ██▄▄  ██▀██ ██▄█▄ ██▀▄▀██   ██▄██ ██ ██ ██▄▄  ██▄▄  ██▄▄  ██▄█
// ▀███▀ ██ ▀██ ██ ██    ▀███▀ ██ ██ ██   ██   ██▄█▀ ▀███▀ ██    ██    ██▄▄▄ ██ ██

store_uniform_buffer :: proc(ubo: Uniform_Buffer) -> Uniform_Buffer_Handle {
	return hm.insert(&ctx.gfx.buffer_manager.uniform_buffers, ubo)
}

get_uniform_buffer :: proc(handle: Uniform_Buffer_Handle) -> (^Uniform_Buffer, bool) {
	return hm.get(&ctx.gfx.buffer_manager.uniform_buffers, handle)
}

detstroy_uniform_buffer :: proc(handle: Uniform_Buffer_Handle) -> bool {
	uniform_buffer, ok := hm.remove(&ctx.gfx.buffer_manager.uniform_buffers, handle)
	destroy_buffer_h(uniform_buffer.buffer_h)
	return ok
}

store_storage_buffer :: proc(sbo: Storage_Buffer) -> Storage_Buffer_Handle {
	return hm.insert(&ctx.gfx.buffer_manager.storage_buffers, sbo)
}

get_storage_buffer :: proc(handle: Storage_Buffer_Handle) -> (^Storage_Buffer, bool) {
	return hm.get(&ctx.gfx.buffer_manager.storage_buffers, handle)
}

detstroy_storage_buffer :: proc(handle: Storage_Buffer_Handle) -> bool {
	storage_buffer, ok := hm.remove(&ctx.gfx.buffer_manager.storage_buffers, handle)
	destroy_buffer_h(storage_buffer.buffer_h)
	return ok
}

//  ██████╗ ██╗      ██████╗ ██████╗  █████╗ ██╗         ██████╗ ███████╗███████╗ ██████╗ ██╗   ██╗██████╗  ██████╗███████╗
// ██╔════╝ ██║     ██╔═══██╗██╔══██╗██╔══██╗██║         ██╔══██╗██╔════╝██╔════╝██╔═══██╗██║   ██║██╔══██╗██╔════╝██╔════╝
// ██║  ███╗██║     ██║   ██║██████╔╝███████║██║         ██████╔╝█████╗  ███████╗██║   ██║██║   ██║██████╔╝██║     █████╗  
// ██║   ██║██║     ██║   ██║██╔══██╗██╔══██║██║         ██╔══██╗██╔══╝  ╚════██║██║   ██║██║   ██║██╔══██╗██║     ██╔══╝  
// ╚██████╔╝███████╗╚██████╔╝██████╔╝██║  ██║███████╗    ██║  ██║███████╗███████║╚██████╔╝╚██████╔╝██║  ██║╚██████╗███████╗
//  ╚═════╝ ╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝    ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚══════╝

@(private)
_init_g_res_manager :: proc() {
	ctx.gfx.g_res_manager = new(Global_Resource_Manager)
	for i in 0 ..< MAX_SLOT_COUNT {
		ctx.gfx.g_res_manager.free_slots[i] = true
	}
}

@(private)
_destroy_g_res_manager :: proc() {
	free(ctx.gfx.g_res_manager)
}

g_resource_set_slot :: proc(slot: int, handle: Resource_Handle, loc := #caller_location) -> bool {
	_assert_slot_value(slot, loc)
	if !g_resource_slot_is_free(slot, loc) {
		return false
	}

	ctx.gfx.g_res_manager.slots[slot] = handle
	ctx.gfx.g_res_manager.free_slots[slot] = false

	return true
}

g_resource_get_slot :: proc(slot: int, loc := #caller_location) -> (Resource_Handle, bool) {
	_assert_slot_value(slot, loc)
	if g_resource_slot_is_free(slot, loc) {
		return {}, false
	}

	return ctx.gfx.g_res_manager.slots[slot], true
}

g_resource_slot_is_free :: proc(slot: int, loc := #caller_location) -> bool {
	_assert_slot_value(slot, loc)
	return ctx.gfx.g_res_manager.free_slots[slot]
}

g_resource_clear_slot :: proc(slot: int, loc := #caller_location) -> Resource_Handle {
	_assert_slot_value(slot, loc)

	ctx.gfx.g_res_manager.free_slots[slot] = true
	return ctx.gfx.g_res_manager.slots[slot]
}

@(private)
_g_res_manager_get_resource_indices :: proc() -> (indices: [MAX_SLOT_COUNT]u32) {
	for slot, i in ctx.gfx.g_res_manager.slots {
		if ctx.gfx.g_res_manager.free_slots[i] {
			indices[i] = max(u32)
			continue
		}

		switch &resource in slot {
		case Buffer_Handle:
			indices[i] = resource.index
		case Texture_Handle:
			indices[i] = resource.index
		}
	}

	return
}

@(private = "file")
_assert_slot_value :: #force_inline proc(slot: int, loc := #caller_location) {
	assert(
		slot >= 0 && slot < MAX_SLOT_COUNT,
		fmt.tprintf("Invalid slot: %d. Valid range is [0, %d) exclusive.", slot, MAX_SLOT_COUNT),
		loc,
	)
}

// ██████╗ ███████╗███████╗███████╗███████╗██████╗ ███████╗██████╗                     
// ██╔══██╗██╔════╝██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝██╔══██╗                    
// ██║  ██║█████╗  █████╗  █████╗  █████╗  ██████╔╝█████╗  ██║  ██║                    
// ██║  ██║██╔══╝  ██╔══╝  ██╔══╝  ██╔══╝  ██╔══██╗██╔══╝  ██║  ██║                    
// ██████╔╝███████╗██║     ██║     ███████╗██║  ██║███████╗██████╔╝                    
// ╚═════╝ ╚══════╝╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝╚═════╝                     
//
// ██████╗ ███████╗███████╗████████╗██████╗ ██╗   ██╗ ██████╗████████╗ ██████╗ ██████╗ 
// ██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔══██╗██║   ██║██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗
// ██║  ██║█████╗  ███████╗   ██║   ██████╔╝██║   ██║██║        ██║   ██║   ██║██████╔╝
// ██║  ██║██╔══╝  ╚════██║   ██║   ██╔══██╗██║   ██║██║        ██║   ██║   ██║██╔══██╗
// ██████╔╝███████╗███████║   ██║   ██║  ██║╚██████╔╝╚██████╗   ██║   ╚██████╔╝██║  ██║
// ╚═════╝ ╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝

_init_deffered_destructor :: proc() {
	ctx.gfx.deffered_destructor = new(Deferred_Destructor)
	ctx.gfx.deffered_destructor.next_index = 0
}

@(private)
_deffered_destructor_add :: proc(resource: Resource) {
	d := ctx.gfx.deffered_destructor
	d.resources[d.next_index] = resource
	d.next_index += 1
	assert(d.next_index < DEFERRED_DESTRUCTOR_SIZE, "Defered destructor is full. Increase DEFERRED_DESTRUCTOR_SIZE.")
}

@(private)
_clear_deffered_destructor :: proc() {
	_deffered_destructor_clear(ctx.gfx.deffered_destructor)
}

@(private)
_destroy_deffered_destructor :: proc() {
	_deffered_destructor_clear(ctx.gfx.deffered_destructor)
	free(ctx.gfx.deffered_destructor)
}

@(private = "file")
_deffered_destructor_clear :: proc(d: ^Deferred_Destructor) {
	for i in 0 ..< d.next_index {
		switch &resource in d.resources[i] {
		case Buffer:
			destroy_buffer(&resource)
		case Buffer_Handle:
			destroy_buffer_h(resource)
		case Texture:
			destroy_texture(&resource)
		case Texture_Handle:
			destroy_texture_h(resource)
		}
	}
	d.next_index = 0
}


// ████████╗███████╗███╗   ███╗██████╗     ██████╗  ██████╗  ██████╗  ██████╗ ██╗     
// ╚══██╔══╝██╔════╝████╗ ████║██╔══██╗    ██╔══██╗██╔═══██╗██╔═══██╗██╔═══██╗██║     
//    ██║   █████╗  ██╔████╔██║██████╔╝    ██████╔╝██║   ██║██║   ██║██║   ██║██║     
//    ██║   ██╔══╝  ██║╚██╔╝██║██╔═══╝     ██╔═══╝ ██║   ██║██║   ██║██║   ██║██║     
//    ██║   ███████╗██║ ╚═╝ ██║██║         ██║     ╚██████╔╝╚██████╔╝╚██████╔╝███████╗
//    ╚═╝   ╚══════╝╚═╝     ╚═╝╚═╝         ╚═╝      ╚═════╝  ╚═════╝  ╚═════╝ ╚══════╝
// A temporary pool acquires resources (materials) for one-frame usage.

@(private)
_init_temp_pools :: proc() {
	ctx.gfx.temp_material_pool = new(Temp_Material_Pool)
	_init_temp_material_pool(ctx.gfx.temp_material_pool, TEMP_POOL_MATERIAL_SIZE)
}

@(private)
_destroy_temp_pools :: proc() {
	_destroy_temp_material_pool(ctx.gfx.temp_material_pool)
	free(ctx.gfx.temp_material_pool)
}

@(require_results)
_temp_pool_acquire_material :: proc() -> Material_Handle {
	return _temp_pool_acquire(ctx.gfx.temp_material_pool)
}

@(private)
_clear_temp_pool :: proc() {
	_temp_pool_clear(ctx.gfx.temp_material_pool)
}

@(private = "file")
_init_temp_pool :: proc(pool: ^$P/Temp_Pool($T), size: int) {
	pool.resources = make([]T, size)
	pool.next_free_resource = 0
}

@(private = "file")
_destroy_temp_pool :: proc(pool: ^$P/Temp_Pool($T)) {
	delete(pool.resources)
}

@(private = "file")
@(require_results)
_temp_pool_acquire :: proc(pool: ^$P/Temp_Pool($T)) -> T {
	when GFX_DEBUG {
		if pool.next_free_resource >= cast(u32)len(pool.resources) {
			log.panicf(
				"Temp %v Pool exhausted: requested element but max %d reached.",
				typeid_of(T),
				len(pool.resources),
			)
		}
	}

	defer pool.next_free_resource += 1

	return pool.resources[pool.next_free_resource]
}

@(private = "file")
_temp_pool_clear :: proc(pool: ^$P/Temp_Pool($T)) {
	pool.next_free_resource = 0
}

@(private = "file")
_init_temp_material_pool :: proc(pool: ^Temp_Material_Pool, size: int, allocator := context) {
	_init_temp_pool(pool, size)
	for i in 0 ..< size {
		pool.resources[i] = create_mtrl_base({}) // FIX: 
	}
}

@(private = "file")
_destroy_temp_material_pool :: proc(pool: ^Temp_Material_Pool) {
	_destroy_temp_pool(pool)
}

// ██████╗ ███████╗███████╗ ██████╗██████╗ ██╗██████╗ ████████╗ ██████╗ ██████╗ 
// ██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
// ██║  ██║█████╗  ███████╗██║     ██████╔╝██║██████╔╝   ██║   ██║   ██║██████╔╝
// ██║  ██║██╔══╝  ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║   ██║   ██║██╔══██╗
// ██████╔╝███████╗███████║╚██████╗██║  ██║██║██║        ██║   ╚██████╔╝██║  ██║
// ╚═════╝ ╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝    ╚═════╝ ╚═╝  ╚═╝
//
// ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗                
// ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗               
// ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝               
// ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗               
// ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║               
// ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝               


Pipeline_Layout_Info :: struct {
	layout_infos:  Pipeline_Set_Layout_Infos,
	push_constant: Maybe(Push_Constant_Range),
}

Descriptor_Layout_Manager :: struct {
	layouts:           map[Pipeline_Set_Layout_Info]vk.DescriptorSetLayout,
	pipeline_layoutes: map[Pipeline_Layout_Info]vk.PipelineLayout,
}

_destroy_descriptor_layout_manager :: proc() {
	for k, layout in ctx.gfx.descriptor_layout_manager.layouts {
		vk.DestroyDescriptorSetLayout(ctx.gfx.vk_state.device, layout, nil)
	}

	for k, pipeline_layout in ctx.gfx.descriptor_layout_manager.pipeline_layoutes {
		vk.DestroyPipelineLayout(ctx.gfx.vk_state.device, pipeline_layout, nil)
	}

	delete(ctx.gfx.descriptor_layout_manager.layouts)
	delete(ctx.gfx.descriptor_layout_manager.pipeline_layoutes)
}

@(require_results)
get_descriptor_set_layouts :: proc(infos: Pipeline_Set_Layout_Infos) -> (layouts: Descriptor_Set_Layouts) {
	for i in 0 ..< infos.len {
		sm.push(&layouts, get_descriptor_set_layout(infos.data[i]))
	}

	return
}

@(require_results)
get_descriptor_set_layout :: proc(info: Pipeline_Set_Layout_Info) -> vk.DescriptorSetLayout {
	layout, ok := ctx.gfx.descriptor_layout_manager.layouts[info]
	if ok do return layout

	layout = _set_info_to_descriptor_set_layout(info)
	ctx.gfx.descriptor_layout_manager.layouts[info] = layout

	return layout
}

@(require_results)
get_pipeline_layout :: proc(info: Pipeline_Layout_Info) -> vk.PipelineLayout {
	pipeline_layout, ok := ctx.gfx.descriptor_layout_manager.pipeline_layoutes[info]
	if ok do return pipeline_layout
	layouts := get_descriptor_set_layouts(info.layout_infos)

	pipeline_layout = _create_pipeline_layout(layouts, info.push_constant)
	ctx.gfx.descriptor_layout_manager.pipeline_layoutes[info] = pipeline_layout

	return pipeline_layout
}

@(private = "file")
@(require_results)
_set_info_to_descriptor_set_layout :: proc(set_info: Pipeline_Set_Layout_Info) -> vk.DescriptorSetLayout {
	descriptor_bindings: sm.Small_Array(MAX_PIPELINE_BINDING_COUNT, vk.DescriptorSetLayoutBinding)
	flags_array: sm.Small_Array(MAX_PIPELINE_BINDING_COUNT, vk.DescriptorBindingFlags)

	use_binding_flags := false

	for i in 0 ..< set_info.binding_infos.len {
		binding := set_info.binding_infos.data[i]
		sm.push(
			&descriptor_bindings,
			vk.DescriptorSetLayoutBinding {
				binding = binding.binding,
				descriptorType = binding.descriptor_type,
				descriptorCount = binding.descriptor_count,
				stageFlags = binding.stage_flags,
				pImmutableSamplers = nil,
			},
		)

		flags, has_flags := binding.flags.?
		if has_flags {
			use_binding_flags = true
			sm.push(&flags_array, flags)
		} else {
			sm.push(&flags_array, vk.DescriptorBindingFlags{})
		}
	}

	p_binding_flags: ^vk.DescriptorSetLayoutBindingFlagsCreateInfo = nil

	if use_binding_flags {
		binding_flags := vk.DescriptorSetLayoutBindingFlagsCreateInfo {
			sType         = .DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO,
			pNext         = nil,
			pBindingFlags = raw_data(sm.slice(&flags_array)),
			bindingCount  = cast(u32)flags_array.len,
		}
		p_binding_flags = &binding_flags
	}

	descriptor_set_layout := vk.DescriptorSetLayout{}

	layout_info := vk.DescriptorSetLayoutCreateInfo {
		sType        = .DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
		pNext        = p_binding_flags,
		bindingCount = cast(u32)descriptor_bindings.len,
		pBindings    = raw_data(sm.slice(&descriptor_bindings)),
		flags        = {.UPDATE_AFTER_BIND_POOL},
	}

	must(
		vk.CreateDescriptorSetLayout(ctx.gfx.vk_state.device, &layout_info, nil, &descriptor_set_layout),
		"failed to create descriptor set layout!",
	)

	return descriptor_set_layout
}

@(private = "file")
@(require_results)
_create_pipeline_layout :: proc(
	descriptor_set_layouts: Descriptor_Set_Layouts,
	push_constant: Maybe(vk.PushConstantRange) = nil,
) -> vk.PipelineLayout {
	descriptor_set_layouts := descriptor_set_layouts
	push, has_push := push_constant.?

	pipeline_layout_info := vk.PipelineLayoutCreateInfo {
		sType                  = .PIPELINE_LAYOUT_CREATE_INFO,
		setLayoutCount         = cast(u32)descriptor_set_layouts.len,
		pSetLayouts            = raw_data(sm.slice(&descriptor_set_layouts)),
		pushConstantRangeCount = 1 if has_push else 0,
		pPushConstantRanges    = &push,
	}
	layout := vk.PipelineLayout{}
	must(vk.CreatePipelineLayout(ctx.gfx.vk_state.device, &pipeline_layout_info, nil, &layout))

	return layout
}

@(private = "file")
_destroy_descriptor_set_layout :: proc(descriptor_set_layout: vk.DescriptorSetLayout) {
	vk.DestroyDescriptorSetLayout(ctx.gfx.vk_state.device, descriptor_set_layout, nil)
}

// ██████╗ ██████╗ ██╗███╗   ███╗██╗████████╗██╗██╗   ██╗███████╗
// ██╔══██╗██╔══██╗██║████╗ ████║██║╚══██╔══╝██║██║   ██║██╔════╝
// ██████╔╝██████╔╝██║██╔████╔██║██║   ██║   ██║██║   ██║█████╗  
// ██╔═══╝ ██╔══██╗██║██║╚██╔╝██║██║   ██║   ██║╚██╗ ██╔╝██╔══╝  
// ██║     ██║  ██║██║██║ ╚═╝ ██║██║   ██║   ██║ ╚████╔╝ ███████╗
// ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝

create_primitive_pipeline :: proc() -> Render_Pipeline_Handle {
	vert_descriptions: Vertex_Input_Descriptions
	sm.append(&vert_descriptions, create_default_vertex_description())

	stages := Stage_Infos{}
	sm.push_back_elems(
		&stages,
		Pipeline_Stage_Info{stage = .Vertex, shader_path = "assets/buildin/shaders/shape.vert"},
		Pipeline_Stage_Info{stage = .Fragment, shader_path = "assets/buildin/shaders/shape.frag"},
	)

	create_info := Create_Pipeline_Info {
		bindless = true,
		vertex_input_descriptions = vert_descriptions,
		stage_infos = stages,
		topology = .Triangle_List,
		rasterizer = {polygon_mode = .Fill, line_width = 1, cull_mode = {}, front_face = .Counter_Clockwise},
		depth = {enable = true, write_enable = true, compare_op = .Less},
	}

	return create_render_pipeline(create_info)
}

create_primitive_square :: proc(size: f32 = 1, allocator := context.allocator) -> Mesh {
	vertices := make([]Vertex, 6, context.allocator)
	vertices[0] = {{size, size, 0.0}, {1, 1}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[1] = {{size, -size, 0.0}, {1, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[2] = {{-size, -size, 0.0}, {0.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}

	vertices[3] = {{size, size, 0.0}, {1, 1}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[4] = {{-size, -size, 0}, {0.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[5] = {{-size, size, 0.0}, {0.0, 1}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}

	return create_mesh(vertices, {})
}

create_primitive_cube :: proc(size: f32 = 1, allocator := context.allocator) -> Mesh {
	vertices := make([]Vertex, 36, context.allocator)
	//                   position         tex_pos        normal              color
	// -Z
	vertices[0] = {{size, size, -size}, {1.0, 1.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[1] = {{size, -size, -size}, {1.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[2] = {{-size, -size, -size}, {0.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[3] = {{-size, -size, -size}, {0.0, 0.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[4] = {{-size, size, -size}, {0.0, 1.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[5] = {{size, size, -size}, {1.0, 1.0}, {0.0, 0.0, -1.0}, {1.0, 1.0, 1.0, 1.0}}

	// +Z
	vertices[6] = {{size, -size, size}, {1.0, 0.0}, {0.0, 0.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[7] = {{size, size, size}, {1.0, 1.0}, {0.0, 0.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[8] = {{-size, -size, size}, {0.0, 0.0}, {0.0, 0.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[9] = {{-size, -size, size}, {0.0, 0.0}, {0.0, 0.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[10] = {{size, size, size}, {1.0, 1.0}, {0.0, 0.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[11] = {{-size, size, size}, {0.0, 1.0}, {0.0, 0.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}

	// -X
	vertices[12] = {{-size, -size, -size}, {0.0, 0.0}, {-1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[13] = {{-size, -size, size}, {1.0, 0.0}, {-1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[14] = {{-size, size, size}, {1.0, 1.0}, {-1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[15] = {{-size, size, size}, {1.0, 1.0}, {-1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[16] = {{-size, size, -size}, {0.0, 1.0}, {-1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[17] = {{-size, -size, -size}, {0.0, 0.0}, {-1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}

	// +X
	vertices[18] = {{size, size, size}, {1.0, 1.0}, {1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[19] = {{size, -size, size}, {1.0, 0.0}, {1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[20] = {{size, -size, -size}, {0.0, 0.0}, {1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[21] = {{size, -size, -size}, {0.0, 0.0}, {1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[22] = {{size, size, -size}, {0.0, 1.0}, {1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[23] = {{size, size, size}, {1.0, 1.0}, {1.0, 0.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}

	// -Y
	vertices[24] = {{-size, -size, -size}, {0.0, 1.0}, {0.0, -1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[25] = {{size, -size, -size}, {1.0, 1.0}, {0.0, -1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[26] = {{size, -size, size}, {1.0, 0.0}, {0.0, -1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[27] = {{size, -size, size}, {1.0, 0.0}, {0.0, -1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[28] = {{-size, -size, size}, {0.0, 0.0}, {0.0, -1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[29] = {{-size, -size, -size}, {0.0, 1.0}, {0.0, -1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}

	// +Y
	vertices[30] = {{size, size, size}, {1.0, 0.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[31] = {{size, size, -size}, {1.0, 1.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[32] = {{-size, size, -size}, {0.0, 1.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[33] = {{-size, size, -size}, {0.0, 1.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[34] = {{-size, size, size}, {0.0, 0.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	vertices[35] = {{size, size, size}, {1.0, 0.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0, 1.0}}
	return create_mesh(vertices, {})
}

draw_square :: proc(frame_data: Frame_Data, camera: ^Camera, position: vec3, scale: vec3, color: vec4) {
	model := ctx.gfx.buildin.square

	material_h := _temp_pool_acquire_material()
	model.materials[0] = material_h
	material, ok := get_material(material_h)
	assert(ok)
	mtrl_set_pipeline(material, ctx.gfx.buildin.pipeline.primitive_h)
	mtrl_base_set_color(material, color)

	transform: Gfx_Transform
	init_trf(&transform)
	trf_set_position(&transform, position)
	trf_set_scale(&transform, scale)

	draw_model(frame_data, model, camera, &transform)
}

draw_square_texture :: proc(
	frame_data: Frame_Data,
	camera: ^Camera,
	position: vec3,
	scale: vec3,
	texture: Texture_Handle,
) {
	model := ctx.gfx.buildin.square

	material_h := _temp_pool_acquire_material()
	model.materials[0] = material_h
	material, ok := get_material(material_h)
	assert(ok)
	mtrl_set_pipeline(material, ctx.gfx.buildin.pipeline.primitive_h)
	mtrl_base_set_texture(material, texture)

	transform: Gfx_Transform
	init_trf(&transform)
	trf_set_position(&transform, position)
	trf_set_scale(&transform, scale)

	draw_model(frame_data, model, camera, &transform)
}
