package ve

// ASCII art generated by: https://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow (with modified 'S' for readability)

import hm "container/handle_map"
import "core:c"
import sm "core:container/small_array"
import "core:fmt"
import "core:log"
import "core:math/linalg/glsl"
import "core:mem"
import "lib/shaderc"
import "lib/vma"
import "math"
import "vendor:glfw"
import vk "vendor:vulkan"

Sample_Count_Flags :: vk.SampleCountFlags
Sample_Count_Flag :: vk.SampleCountFlag
Sampler :: vk.Sampler
Semaphore :: vk.Semaphore
Push_Constant_Range :: vk.PushConstantRange
Device_Size :: vk.DeviceSize
Command_Buffer :: vk.CommandBuffer
Pipeline_Stage_Flags :: vk.PipelineStageFlags
Descriptor_Set :: vk.DescriptorSet

Vulkan_State :: struct {
	enabled_layer_names:      [dynamic]cstring,
	instance:                 vk.Instance,
	physical_device:          vk.PhysicalDevice,
	physical_device_property: vk.PhysicalDeviceProperties,
	memory_propertices:       vk.PhysicalDeviceMemoryProperties,
	device:                   vk.Device,
	dbg_messenger:            Maybe(vk.DebugUtilsMessengerEXT),
	allocator:                vma.Allocator,
	graphics_queue:           vk.Queue,
	present_queue:            vk.Queue,
	surface:                  vk.SurfaceKHR,
	command_pool:             vk.CommandPool,
	descriptor_pool:          vk.DescriptorPool,
}

Graphics_Limits :: struct {
	max_sample_count:       Sample_Count_Flag,
	max_sampler_anisotropy: f32,
}

Graphics_Attachment_Flags :: distinct bit_set[Graphics_Attachment_Flag]
Graphics_Attachment_Flag :: enum {
	Depth,
	Stencil,
}

Graphics_Init_Info :: struct {
	swapchain_sample_count: Sample_Count_Flag,
	attachments:            Graphics_Attachment_Flags,
}

Swapchain_Configuration :: struct {
	present_mode:         vk.PresentModeKHR,
	depth_format:         Format,
	depth_stencil_format: Format,
	vk_surface_format:    vk.SurfaceFormatKHR,
}

Graphics :: struct {
	vk_state:                  Vulkan_State,
	image_available_semaphore: vk.Semaphore,
	fence:                     vk.Fence,
	limits:                    Graphics_Limits,
	cmd:                       vk.CommandBuffer,
	swapchain_cfg:             Swapchain_Configuration,
	frame:                     Frame_Data,
	render_started:            bool,
	// managers
	swapchain:                 ^Swapchain,
	buffer_manager:            ^Buffer_Manager,
	pipeline_manager:          ^Pipeline_Manager,
	descriptor_layout_manager: Descriptor_Layout_Manager,
	bindless:                  ^Bindless,
	deffered_destructor:       ^Deferred_Destructor,
}

Resource :: union {
	Buffer_Data,
	Texture_Data,
	Buffer,
	Texture,
}

NIL_HANDLE :: Buffer {
	index = max(u32),
}

Resource_Handle :: union {
	Uniform_Buffer,
	Storage_Buffer,
	Buffer,
	Texture,
}

Deferred_Destructor :: struct {
	resources:  [DEFERRED_DESTRUCTOR_SIZE]Resource,
	next_index: int,
}

@(private)
Single_Command :: struct {
	cmd: vk.CommandBuffer,
}

// SWAP CHAIN

Swapchain :: struct {
	swapchain:                  vk.SwapchainKHR,
	color_format:               Format,
	width, height:              int,
	sample_count:               Sample_Count_Flag,
	msaa_color_texture:         Maybe(Texture_Data),
	depth_image:                Texture_Data,
	image_index:                u32,
	images:                     []vk.Image,
	image_views:                []vk.ImageView,
	frame_buffers:              []vk.Framebuffer,
	render_finished_semaphores: []vk.Semaphore,
}

// FEATURES

Physical_Device_Features :: struct {
	dynamic_rendering_local_read: vk.PhysicalDeviceDynamicRenderingLocalReadFeatures,
	// ^
	// | pNext
	features13:                   vk.PhysicalDeviceVulkan13Features,
	// ^
	// | pNext
	features12:                   vk.PhysicalDeviceVulkan12Features,
	// ^
	// | pNext
	features:                     vk.PhysicalDeviceFeatures2,
}

// MODEL

Vertex :: struct {
	position:  vec3,
	tex_coord: vec2,
	normal:    vec3,
}

Mesh :: struct {
	vbo:          Buffer,
	ebo:          Maybe(Buffer),
	vertex_count: int,
	index_count:  int,
}

// FRAME

Frame_Status :: enum {
	Success,
	IncorrectSwapchainSize,
}

Surface_Info_Type :: enum {
	None,
	Swapchain,
	Surface,
}

Surface_Info :: struct {
	type:                     Surface_Info_Type,
	sample_count:             Sample_Count_Flag,
	depth_format:             Format,
	color_formats:            sm.Small_Array(MAX_COLOR_ATTACHMENTS, Format),
	active_color_attachments: sm.Small_Array(MAX_COLOR_ATTACHMENTS, int), // FIX:
	width:                    int,
	height:                   int,
}

Frame_Data :: struct {
	status:            Frame_Status,
	surface_info:      Surface_Info,
	camera:            Buffer,
	swapchain_resized: bool,
}

Render_Frame :: struct {
	state:       bool,
	image_index: u32,
}

Sync_Data :: struct {
	wait_semaphore_infos: []vk.SemaphoreSubmitInfo,
}

// BINDLESS

Texture :: distinct hm.Handle
INVALID_TEXTURE_HANDLE :: Texture{max(u32), max(u32)}
Buffer :: distinct hm.Handle
INVALID_BUFFER_HANDLE :: Buffer{max(u32), max(u32)}

Bindless :: struct {
	set:        vk.DescriptorSet,
	set_layout: vk.DescriptorSetLayout,
	textures:   hm.Handle_Map(Texture_Data, Texture),
	buffers:    hm.Handle_Map(Buffer_Data, Buffer),
}

// *_norm_*
// Normalized formats automatically convert integer color values to floating-point ranges in shaders.
//
// For example:
//   format     |      input       |    shader
// RGB_norm_u8: | (255,    0, 128) | (1,  0, 0.5..)
// RGB_norm_i8: | (127, -128,   0) | (1, -1,   0)
// ---
// *_scaled_*
// Scaled formats convert integer values directly to floating-point in shaders.
//
// For example:
//   format       |     input        |        shader
// RGB_scaled_u8: | (255,    0, 128) | (255.0,    0.0, 128.0)
// RGB_scaled_i8: | (127, -128,   0) | (127.0, -128.0,   0.0)
// ---
// *_srgb_u*
// The R, G, and B components are unsigned normalized values that represent values using sRGB nonlinear encoding,
// while the A component (if one exists) is a regular unsigned normalized value.
//
// NOTE: Blending is only defined for floating-point, _norm_, and _srgb_u formats.
// Transfer function: https://registry.khronos.org/DataFormat/specs/1.4/dataformat.1.4.html#TRANSFER_SRGB
// May be useful: https://learnopengl.com/Advanced-Lighting/Gamma-Correction
Format :: enum i32 {
	None            = 0,
	// 8 bits
	R_norm_u8       = 9,
	R_norm_i8       = 10,
	R_scaled_u8     = 11,
	R_scaled_i8     = 12,
	R_u8            = 13,
	R_i8            = 14,
	RG_norm_u8      = 16,
	RG_norm_i8      = 17,
	RG_scaled_u8    = 18,
	RG_scaled_i8    = 19,
	RG_u8           = 20,
	RG_i8           = 21,
	RGB_norm_u8     = 23,
	RGB_norm_i8     = 24,
	RGB_scaled_u8   = 25,
	RGB_scaled_i8   = 26,
	RGB_u8          = 27,
	RGB_i8          = 28,
	BGR_norm_u8     = 30,
	BGR_norm_i8     = 31,
	BGR_scaled_u8   = 32,
	BGR_scaled_i8   = 33,
	BGR_u8          = 34,
	BGR_i8          = 35,
	RGBA_norm_u8    = 37,
	RGBA_norm_i8    = 38,
	RGBA_scaled_u8  = 39,
	RGBA_scaled_i8  = 40,
	RGBA_u8         = 41,
	RGBA_i8         = 42,
	RGBA_srgb_u8    = 43,
	BGRA_norm_u8    = 44,
	BGRA_norm_i8    = 45,
	BGRA_scaled_u8  = 46,
	BGRA_scaled_i8  = 47,
	BGRA_u8         = 48,
	BGRA_i8         = 49,
	BGRA_srgb_u8    = 50,
	// 16 bits
	R_norm_u16      = 70,
	R_norm_i16      = 71,
	R_scaled_u16    = 72,
	R_scaled_i16    = 73,
	R_u16           = 74,
	R_i16           = 75,
	R_f16           = 76,
	RG_norm_u16     = 77,
	RG_norm_i16     = 78,
	RG_scaled_u16   = 79,
	RG_scaled_i16   = 80,
	RG_u16          = 81,
	RG_i16          = 82,
	RG_f16          = 83,
	RGB_norm_u16    = 84,
	RGB_norm_i16    = 85,
	RGB_scaled_u16  = 86,
	RGB_scaled_i16  = 87,
	RGB_u16         = 88,
	RGB_i16         = 89,
	RGB_f16         = 90,
	RGBA_norm_u16   = 91,
	RGBA_norm_i16   = 92,
	RGBA_scaled_u16 = 93,
	RGBA_scaled_i16 = 94,
	RGBA_u16        = 95,
	RGBA_i16        = 96,
	RGBA_f16        = 97,
	// 32 bits
	R_u32           = 98,
	R_i32           = 99,
	R_f32           = 100,
	RG_u32          = 101,
	RG_i32          = 102,
	RG_f32          = 103,
	RGB_u32         = 104,
	RGB_i32         = 105,
	RGB_f32         = 106,
	RGBA_u32        = 107,
	RGBA_i32        = 108,
	RGBA_f32        = 109,
	// 64 bits
	R_u64           = 110,
	R_i64           = 111,
	R_f64           = 112,
	RG_u64          = 113,
	RG_i64          = 114,
	RG_f64          = 115,
	RGB_u64         = 116,
	RGB_i64         = 117,
	RGB_f64         = 118,
	RGBA_u64        = 119,
	RGBA_i64        = 120,
	RGBA_f64        = 121,
	// depth
	// depth_stencil
	D_f32           = 126,
	D_f32_S_u8      = 130,
}

@(private)
_get_cmd :: proc() -> Command_Buffer {return ctx.gfx.cmd}

begin_pass :: proc(loc := #caller_location) {
	assert(!ctx.gfx.render_started, "Call end_pass() after begin_pass()", loc)

	_update_buffers()

	defer ctx.gfx.render_started = true

	frame_data := Frame_Data {
		status = .Success,
	}

	// Wait for previous frame
	must(vk.WaitForFences(ctx.gfx.vk_state.device, 1, &ctx.gfx.fence, true, max(u64)))

	images: u32 = cast(u32)len(ctx.gfx.swapchain.images)
	acquire_result := vk.AcquireNextImageKHR(
		device = ctx.gfx.vk_state.device,
		swapchain = ctx.gfx.swapchain.swapchain,
		timeout = max(u64),
		semaphore = ctx.gfx.image_available_semaphore,
		fence = {},
		pImageIndex = &ctx.gfx.swapchain.image_index,
	)

	#partial switch acquire_result {
	case .ERROR_OUT_OF_DATE_KHR:
		frame_data.status = .IncorrectSwapchainSize
		return
	case .SUCCESS, .SUBOPTIMAL_KHR:
	case:
		log.panicf("acquire next image failure: %v", acquire_result)
	}

	must(vk.ResetFences(ctx.gfx.vk_state.device, 1, &ctx.gfx.fence))
	must(vk.ResetCommandBuffer(_get_cmd(), {}))

	begin_info := vk.CommandBufferBeginInfo {
		sType = .COMMAND_BUFFER_BEGIN_INFO,
	}
	must(vk.BeginCommandBuffer(_get_cmd(), &begin_info))
}

end_pass :: proc() {
	if !ctx.gfx.render_started {
		log.error("Call begin_pass() before end_pass()")
	}
	defer ctx.gfx.render_started = false

	image_semaphore := ctx.gfx.swapchain.render_finished_semaphores[ctx.gfx.swapchain.image_index]
	image := ctx.gfx.swapchain.images[ctx.gfx.swapchain.image_index] // FIXME:

	must(vk.EndCommandBuffer(_get_cmd()))

	// wait_semaphore_infos := merge(
	// 	ctx.gfx.wait_semaphore_infos[:],
	// 	[]vk.SemaphoreSubmitInfo {
	// 		{
	// 			sType       = .SEMAPHORE_SUBMIT_INFO,
	// 			semaphore   = ctx.gfx.image_available_semaphore,
	// 			stageMask   = {.ALL_COMMANDS}, // {.COLOR_ATTACHMENT_OUTPUT},
	// 			deviceIndex = 0,
	// 		},
	// 	},
	// 	context.temp_allocator,
	// )
	wait_semaphore_infos := []vk.SemaphoreSubmitInfo {
		{
			sType       = .SEMAPHORE_SUBMIT_INFO,
			semaphore   = ctx.gfx.image_available_semaphore,
			stageMask   = {.ALL_COMMANDS}, // {.COLOR_ATTACHMENT_OUTPUT}, // FIXME:
			deviceIndex = 0,
		},
	}

	comand_buffer_info := vk.CommandBufferSubmitInfo {
		sType         = .COMMAND_BUFFER_SUBMIT_INFO,
		commandBuffer = _get_cmd(),
	}

	signal_semaphore_info := vk.SemaphoreSubmitInfo {
		sType     = .SEMAPHORE_SUBMIT_INFO,
		semaphore = image_semaphore,
		stageMask = {.ALL_COMMANDS},
	}

	submit_info := vk.SubmitInfo2 {
		sType                    = .SUBMIT_INFO_2,
		waitSemaphoreInfoCount   = cast(u32)len(wait_semaphore_infos),
		pWaitSemaphoreInfos      = raw_data(wait_semaphore_infos),
		commandBufferInfoCount   = 1,
		pCommandBufferInfos      = &comand_buffer_info,
		signalSemaphoreInfoCount = 1,
		pSignalSemaphoreInfos    = &signal_semaphore_info,
	}
	must(vk.QueueSubmit2(ctx.gfx.vk_state.graphics_queue, 1, &submit_info, ctx.gfx.fence))

	present_info := vk.PresentInfoKHR {
		sType              = .PRESENT_INFO_KHR,
		waitSemaphoreCount = 1,
		pWaitSemaphores    = &image_semaphore,
		swapchainCount     = 1,
		pSwapchains        = &ctx.gfx.swapchain.swapchain,
		pImageIndices      = &ctx.gfx.swapchain.image_index,
	}
	present_result := vk.QueuePresentKHR(ctx.gfx.vk_state.present_queue, &present_info)

	switch {
	case present_result == .ERROR_OUT_OF_DATE_KHR || present_result == .SUBOPTIMAL_KHR:
		ctx.gfx.frame.status = .IncorrectSwapchainSize
	case present_result == .SUCCESS:
	case:
		log.panicf("vulkan: present failure: %v", present_result)
	}

	if ctx.gfx.frame.swapchain_resized {
		ctx.gfx.frame.swapchain_resized = false
	}

	if ctx.gfx.frame.status == .IncorrectSwapchainSize {
		ctx.gfx.frame.swapchain_resized = true
		_on_screen_resized()
	}

	_clear_deffered_destructor()
}

begin_draw :: proc(clear_color: vec4 = {0.0, 0.0, 0.0, 1.0}) {
	_cmd_image_transition_layout(
		_get_cmd(),
		ctx.gfx.swapchain.images[ctx.gfx.swapchain.image_index],
		.UNDEFINED,
		.COLOR_ATTACHMENT_OPTIMAL,
		vk.ImageSubresourceRange{aspectMask = {.COLOR}, layerCount = 1, levelCount = 1},
	)

	color_attachment_info := _swapchaint_get_color_attachment_info(clear_color)

	depth_stencil_clear_value := vk.ClearValue {
		depthStencil = {1, 0},
	}

	depth_stencil_attachment_info := vk.RenderingAttachmentInfo {
		sType       = .RENDERING_ATTACHMENT_INFO,
		pNext       = nil,
		imageView   = ctx.gfx.swapchain.depth_image.view,
		imageLayout = .DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
		loadOp      = .CLEAR,
		storeOp     = .DONT_CARE,
		clearValue  = depth_stencil_clear_value,
	}

	rendering_info := vk.RenderingInfo {
		sType = .RENDERING_INFO,
		renderArea = {extent = {width = cast(u32)ctx.gfx.swapchain.width, height = cast(u32)ctx.gfx.swapchain.height}},
		layerCount = 1,
		colorAttachmentCount = 1,
		pColorAttachments = &color_attachment_info,
		pDepthAttachment = &depth_stencil_attachment_info,
		pStencilAttachment = &depth_stencil_attachment_info if _has_stencil_component(ctx.gfx.swapchain.depth_image.format) else nil,
	}

	vk.CmdBeginRendering(_get_cmd(), &rendering_info)

	surface_info := Surface_Info {
		type         = .Swapchain,
		sample_count = ctx.gfx.swapchain.sample_count,
		depth_format = ctx.gfx.swapchain.depth_image.format,
		width        = ctx.gfx.swapchain.width,
		height       = ctx.gfx.swapchain.height,
	}
	sm.push(&surface_info.color_formats, ctx.gfx.swapchain.color_format)

	ctx.gfx.frame.surface_info = surface_info

	cmd_set_full_viewport_scissor()
}

end_draw :: proc() {
	vk.CmdEndRendering(_get_cmd())

	_cmd_image_transition_layout(
		_get_cmd(),
		ctx.gfx.swapchain.images[ctx.gfx.swapchain.image_index],
		.COLOR_ATTACHMENT_OPTIMAL,
		.PRESENT_SRC_KHR,
	)
}

// @(private)
// _create_semapthore :: proc() -> vk.Semaphore {
// 	semaphore: vk.Semaphore
// 	info := vk.SemaphoreCreateInfo {
// 		sType = .SEMAPHORE_CREATE_INFO,
// 	}
// 	vk.CreateSemaphore(ctx.gfx.vk_state.device, &info, nil, &semaphore)
// 	return semaphore
// }

// TODO: add semaphore pool
begin_compute :: proc() {
	log.panic("Not implemented")
	// vk.WaitForFences(ctx.gfx.vk_state.device, 1, &ctx.gfx.fence, true, max(u64))
	// vk.ResetFences(ctx.gfx.vk_state.device, 1, &ctx.gfx.fence)
	// vk.ResetCommandBuffer(ctx.gfx.cmd, {})
	// being_info := vk.CommandBufferBeginInfo {
	// 	sType = .COMMAND_BUFFER_BEGIN_INFO,
	// 	flags = {},
	// }
	// vk.BeginCommandBuffer(ctx.gfx.cmd, &being_info)
}

end_compute :: proc() {
	log.panic("Not implemented")
	// semaphore := _create_semapthore()
	//
	// vk.EndCommandBuffer(ctx.gfx.cmd)
	// comand_buffer_info := vk.CommandBufferSubmitInfo {
	// 	sType         = .COMMAND_BUFFER_SUBMIT_INFO,
	// 	commandBuffer = ctx.gfx.cmd,
	// }
	// semaphore_info := vk.SemaphoreSubmitInfo {
	// 	sType       = .SEMAPHORE_SUBMIT_INFO,
	// 	semaphore   = semaphore,
	// 	stageMask   = {.COMPUTE_SHADER},
	// 	deviceIndex = 0,
	// }
	// submit_info := vk.SubmitInfo2 {
	// 	sType                    = .SUBMIT_INFO_2,
	// 	commandBufferInfoCount   = 1,
	// 	pCommandBufferInfos      = &comand_buffer_info,
	// 	signalSemaphoreInfoCount = 1,
	// 	pSignalSemaphoreInfos    = &semaphore_info,
	// }
	// must(vk.QueueSubmit2(ctx.gfx.vk_state.graphics_queue, 1, &submit_info, ctx.gfx.fence))
	// append(&ctx.gfx.wait_semaphore_infos, semaphore_info)
}

@(private)
_on_screen_resized :: proc() {
	// Don't do anything when minimized.
	for w, h := glfw.GetFramebufferSize(ctx.window.id);
	    w == 0 || h == 0;
	    w, h = glfw.GetFramebufferSize(ctx.window.id) {
		glfw.WaitEvents()

		// Handle closing while minimized.
		if glfw.WindowShouldClose(ctx.window.id) {return}
	}
	_recreate_swapchain()
}

wait_render_completion :: proc() {
	vk.DeviceWaitIdle(ctx.gfx.vk_state.device)
}

//  ██████╗███╗   ███╗██████╗ 
// ██╔════╝████╗ ████║██╔══██╗
// ██║     ██╔████╔██║██║  ██║
// ██║     ██║╚██╔╝██║██║  ██║
// ╚██████╗██║ ╚═╝ ██║██████╔╝
//  ╚═════╝╚═╝     ╚═╝╚═════╝ 

cmd_set_full_viewport_scissor :: proc(loc := #caller_location) {
	width := get_screen_width()
	height := get_screen_height()

	cmd_set_viewport(width, height, loc = loc)
	cmd_set_scissor(width, height, loc = loc)
}

cmd_set_viewport :: proc(width, height: int, max_depth: f32 = 1, loc := #caller_location) {

	viewport := vk.Viewport {
		width    = cast(f32)width,
		height   = cast(f32)height,
		maxDepth = 1,
	}
	vk.CmdSetViewport(_get_cmd(), 0, 1, &viewport)
}

cmd_set_scissor :: proc(width, height: int, offset: ivec2 = 0, loc := #caller_location) {

	scissor := vk.Rect2D {
		extent = {width = cast(u32)width, height = cast(u32)height},
		offset = {x = offset.x, y = offset.y},
	}
	vk.CmdSetScissor(_get_cmd(), 0, 1, &scissor)
}

cmd_bind_vertex_buffer :: proc(buffer: Buffer, binding: u32, offset := vk.DeviceSize{}, loc := #caller_location) {
	b := _get_buffer_h(buffer)
	assert(.Vertex in b.usage, loc = loc)

	offset := offset
	buffer := buffer

	vk.CmdBindVertexBuffers(_get_cmd(), binding, 1, &b.id, &offset)
}

cmd_bind_index_buffer :: proc(
	buffer: Buffer,
	offset := vk.DeviceSize{},
	index_type := vk.IndexType.UINT16,
	loc := #caller_location,
) {
	b := _get_buffer_h(buffer, loc)
	assert(.Index in b.usage, loc = loc)

	offset := offset
	buffer := buffer

	vk.CmdBindIndexBuffer(_get_cmd(), b.id, offset, index_type)
}

cmd_push_constants :: proc(layout: Pipeline_Layout, const: ^$T, stages := vk.ShaderStageFlags_ALL_GRAPHICS) {
	vk.CmdPushConstants(_get_cmd(), layout, stages, 0, size_of(const^), const)
}

cmd_draw :: proc(vertex_count: int, instance_count: u32 = 1, loc := #caller_location) {
	vk.CmdDraw(_get_cmd(), cast(u32)vertex_count, instance_count, 0, 0)
}

cmd_draw_indexed :: proc(vertex_count: int, instance_count: u32 = 1, loc := #caller_location) {
	vk.CmdDrawIndexed(_get_cmd(), cast(u32)vertex_count, instance_count, 0, 0, 0)
}

cmd_bind_graphics_pipeline :: proc(pipeline: Graphics_Pipeline, loc := #caller_location) -> Pipeline_Layout {
	graphics_pipeline := _graphics_pipeline_get_variant(_get_graphics_pipeline(pipeline, loc), loc)
	vk.CmdBindPipeline(_get_cmd(), .GRAPHICS, graphics_pipeline.id)
	cmd_bind_descriptor_set_graphics(graphics_pipeline, _get_descriptor_set_bindless())
	return _get_pipeline_layout(graphics_pipeline.layout)
}

cmd_bind_compute_pipeline :: proc(pipeline: Compute_Pipeline, loc := #caller_location) -> Pipeline_Layout {
	p := _get_compute_pipeline(pipeline, loc)
	vk.CmdBindPipeline(_get_cmd(), .COMPUTE, p.id)
	return _get_pipeline_layout(p.layout)
}

cmd_bind_descriptor_set_graphics :: proc(
	pipeline: ^Pipeline,
	descriptor_sets: ..vk.DescriptorSet,
	loc := #caller_location,
) {
	_cmd_bind_descriptor_set(_get_cmd(), .GRAPHICS, pipeline, descriptor_sets, loc)
}

cmd_bind_descriptor_set_compute :: proc(
	pipeline: ^Pipeline,
	descriptor_sets: ..vk.DescriptorSet,
	loc := #caller_location,
) {
	_cmd_bind_descriptor_set(_get_cmd(), .COMPUTE, pipeline, descriptor_sets, loc)
}

@(private = "file")
_cmd_bind_descriptor_set :: proc(
	cmd: Command_Buffer,
	bind_point: vk.PipelineBindPoint,
	pipeline: ^Pipeline,
	descriptor_sets: []vk.DescriptorSet,
	loc := #caller_location,
) {

	layout := _get_pipeline_layout(pipeline.layout)

	vk.CmdBindDescriptorSets(
		cmd,
		bind_point,
		layout,
		0,
		cast(u32)len(descriptor_sets),
		raw_data(descriptor_sets),
		0,
		nil,
	)
}

cmd_dispatch :: proc(
	pipeline: Compute_Pipeline,
	buffer: Buffer,
	group_count: uvec3,
	trf: Maybe(mat4) = nil,
	handles: Handles = {},
) {
	layout := cmd_bind_compute_pipeline(pipeline)

	consts_data := _get_push_constants_data(trf, handles)
	cmd_push_constants(layout, &consts_data, {.COMPUTE})

	bindless_descriptor_set := _get_descriptor_set_bindless()
	vk.CmdBindDescriptorSets(ctx.gfx.cmd, .COMPUTE, layout, 0, 1, &bindless_descriptor_set, 0, nil)
	vk.CmdDispatch(_get_cmd(), group_count.x, group_count.y, group_count.z)

	b := _get_buffer_h(buffer)
	_, dst_access, dst_stage := _buffer_get_usage_and_dst_access_stage_mask(b.usage)
	_cmd_buffer_barrier(_get_cmd(), b.id, {.SHADER_WRITE, .SHADER_READ}, dst_access, {.COMPUTE_SHADER}, dst_stage)
}

@(require_results)
begin_single_cmd :: proc() -> Single_Command {
	alloc_info := vk.CommandBufferAllocateInfo {
		sType              = .COMMAND_BUFFER_ALLOCATE_INFO,
		level              = .PRIMARY,
		commandPool        = ctx.gfx.vk_state.command_pool,
		commandBufferCount = 1,
	}

	command_buffer: vk.CommandBuffer
	must(vk.AllocateCommandBuffers(ctx.gfx.vk_state.device, &alloc_info, &command_buffer))

	begin_info := vk.CommandBufferBeginInfo {
		sType = .COMMAND_BUFFER_BEGIN_INFO,
		flags = {.ONE_TIME_SUBMIT},
	}
	must(vk.BeginCommandBuffer(command_buffer, &begin_info))

	return Single_Command{cmd = command_buffer}
}

end_single_cmd :: proc(single_command: Single_Command) {
	command_buffer := single_command.cmd

	must(vk.EndCommandBuffer(command_buffer))

	submit_info := vk.SubmitInfo {
		sType              = .SUBMIT_INFO,
		commandBufferCount = 1,
		pCommandBuffers    = &command_buffer,
	}

	must(vk.QueueSubmit(ctx.gfx.vk_state.graphics_queue, 1, &submit_info, 0))
	must(vk.QueueWaitIdle(ctx.gfx.vk_state.graphics_queue))

	vk.FreeCommandBuffers(ctx.gfx.vk_state.device, ctx.gfx.vk_state.command_pool, 1, &command_buffer)
}

@(private)
_cmd_buffer_barrier :: proc(
	cmd: vk.CommandBuffer,
	vk_buffer: vk.Buffer,
	src_access_mask: vk.AccessFlags2,
	dst_access_mask: vk.AccessFlags2,
	src_stage_mask: vk.PipelineStageFlags2,
	dst_stage_mask: vk.PipelineStageFlags2,
) {
	buffer_barrier := vk.BufferMemoryBarrier2 {
		sType               = .BUFFER_MEMORY_BARRIER_2,
		srcAccessMask       = src_access_mask,
		dstAccessMask       = dst_access_mask,
		srcStageMask        = src_stage_mask,
		dstStageMask        = dst_stage_mask,
		srcQueueFamilyIndex = vk.QUEUE_FAMILY_IGNORED,
		dstQueueFamilyIndex = vk.QUEUE_FAMILY_IGNORED,
		buffer              = vk_buffer,
		offset              = 0,
		size                = cast(vk.DeviceSize)vk.WHOLE_SIZE,
	}

	dep_info := vk.DependencyInfo {
		sType                    = .DEPENDENCY_INFO,
		dependencyFlags          = {},
		memoryBarrierCount       = 0,
		pMemoryBarriers          = nil,
		bufferMemoryBarrierCount = 1,
		pBufferMemoryBarriers    = &buffer_barrier,
		imageMemoryBarrierCount  = 0,
	}

	vk.CmdPipelineBarrier2(cmd, &dep_info)
}

@(private)
_cmd_copy_buffer_to_image :: proc(
	cmd: vk.CommandBuffer,
	buffer: vk.Buffer,
	image: vk.Image,
	regions: []vk.BufferImageCopy,
) {
	vk.CmdCopyBufferToImage(cmd, buffer, image, .TRANSFER_DST_OPTIMAL, cast(u32)len(regions), raw_data(regions))
}

@(private)
_cmd_image_transition_layout :: proc(
	cmd: vk.CommandBuffer,
	image: vk.Image,
	old_layout: vk.ImageLayout,
	new_layout: vk.ImageLayout,
	subresource_range: vk.ImageSubresourceRange = {aspectMask = {.COLOR}, levelCount = 1, layerCount = 1},
) {
	src_stage, dst_stage: vk.PipelineStageFlags2
	src_access, dst_access: vk.AccessFlags2

	if old_layout == .UNDEFINED && new_layout == .TRANSFER_DST_OPTIMAL {
		src_access = {}
		dst_access = {.TRANSFER_WRITE}

		src_stage = {}
		dst_stage = {.TRANSFER}
	} else if old_layout == .TRANSFER_DST_OPTIMAL && new_layout == .SHADER_READ_ONLY_OPTIMAL {
		src_access = {.TRANSFER_WRITE}
		dst_access = {.SHADER_READ}

		src_stage = {.TRANSFER}
		dst_stage = {.VERTEX_SHADER, .FRAGMENT_SHADER}
	} else if old_layout == .UNDEFINED && new_layout == .DEPTH_STENCIL_ATTACHMENT_OPTIMAL {
		src_access = {}
		dst_access = {.DEPTH_STENCIL_ATTACHMENT_READ, .DEPTH_STENCIL_ATTACHMENT_WRITE}

		src_stage = {}
		dst_stage = {.EARLY_FRAGMENT_TESTS}
	} else if old_layout == .DEPTH_STENCIL_ATTACHMENT_OPTIMAL && new_layout == .SHADER_READ_ONLY_OPTIMAL {
		src_access = {.DEPTH_STENCIL_ATTACHMENT_WRITE}
		dst_access = {.SHADER_READ}

		src_stage = {.EARLY_FRAGMENT_TESTS}
		dst_stage = {.VERTEX_SHADER, .FRAGMENT_SHADER}
	} else if old_layout == .SHADER_READ_ONLY_OPTIMAL && new_layout == .DEPTH_STENCIL_ATTACHMENT_OPTIMAL {
		src_access = {.SHADER_READ}
		dst_access = {.DEPTH_STENCIL_ATTACHMENT_WRITE}

		src_stage = {.VERTEX_SHADER, .FRAGMENT_SHADER}
		dst_stage = {.EARLY_FRAGMENT_TESTS}
	} else if old_layout == .UNDEFINED && new_layout == .COLOR_ATTACHMENT_OPTIMAL {
		src_access = {}
		dst_access = {.COLOR_ATTACHMENT_WRITE}

		src_stage = {.ALL_COMMANDS}
		dst_stage = {.COLOR_ATTACHMENT_OUTPUT}
	} else if old_layout == .COLOR_ATTACHMENT_OPTIMAL && new_layout == .PRESENT_SRC_KHR {
		src_access = {.COLOR_ATTACHMENT_WRITE}
		dst_access = {}

		src_stage = {.COLOR_ATTACHMENT_OUTPUT}
		dst_stage = {}
	} else if old_layout == .COLOR_ATTACHMENT_OPTIMAL && new_layout == .SHADER_READ_ONLY_OPTIMAL {
		src_access = {.COLOR_ATTACHMENT_WRITE}
		dst_access = {.MEMORY_READ}

		src_stage = {.COLOR_ATTACHMENT_OUTPUT}
		dst_stage = {.VERTEX_SHADER, .FRAGMENT_SHADER}
	} else if old_layout == .SHADER_READ_ONLY_OPTIMAL && new_layout == .COLOR_ATTACHMENT_OPTIMAL {
		src_access = {.MEMORY_READ}
		dst_access = {.COLOR_ATTACHMENT_WRITE}

		src_stage = {.VERTEX_SHADER, .FRAGMENT_SHADER}
		dst_stage = {.COLOR_ATTACHMENT_OUTPUT}
	} else if old_layout == .TRANSFER_DST_OPTIMAL && new_layout == .TRANSFER_SRC_OPTIMAL {
		src_access = {.TRANSFER_WRITE}
		dst_access = {.TRANSFER_READ}

		src_stage = {.TRANSFER}
		dst_stage = {.TRANSFER}
	} else if old_layout == .TRANSFER_SRC_OPTIMAL && new_layout == .SHADER_READ_ONLY_OPTIMAL {
		src_access = {.TRANSFER_READ}
		dst_access = {.SHADER_READ}

		src_stage = {.TRANSFER}
		dst_stage = {.VERTEX_SHADER, .FRAGMENT_SHADER}
	} else {
		log.panicf("unsuported layout transition!\nold_layout %v \nnew_layout: %v", old_layout, new_layout)
	}

	barrier := vk.ImageMemoryBarrier2 {
		sType               = .IMAGE_MEMORY_BARRIER_2,
		oldLayout           = old_layout,
		newLayout           = new_layout,
		srcQueueFamilyIndex = vk.QUEUE_FAMILY_IGNORED,
		dstQueueFamilyIndex = vk.QUEUE_FAMILY_IGNORED,
		image               = image,
		subresourceRange    = subresource_range,
		srcStageMask        = src_stage,
		srcAccessMask       = src_access,
		dstAccessMask       = dst_access,
		dstStageMask        = dst_stage,
	}

	dependency_info := vk.DependencyInfo {
		sType                   = .DEPENDENCY_INFO,
		imageMemoryBarrierCount = 1,
		pImageMemoryBarriers    = &barrier,
		dependencyFlags         = {},
	}

	vk.CmdPipelineBarrier2(cmd, &dependency_info)
}

_cmd_copy_buffer :: proc(cmd: Command_Buffer, src_buffer: vk.Buffer, dst_buffer: vk.Buffer, size: vk.DeviceSize) {
	copy := vk.BufferCopy {
		srcOffset = 0,
		dstOffset = 0,
		size      = size,
	}
	vk.CmdCopyBuffer(cmd, src_buffer, dst_buffer, 1, &copy)
}


// Mesh

create_mesh :: proc(vertices: []Vertex, indices: []u16, loc := #caller_location) -> Mesh {
	assert(len(vertices) > 0, loc = loc)

	vertices_size := cast(vk.DeviceSize)(size_of(vertices[0]) * len(vertices))
	vertex_buffer := create_buffer({.Vertex}, vertices_size, raw_data(vertices), loc)

	mesh := Mesh {
		vertex_count = len(vertices),
		vbo          = vertex_buffer,
	}

	if len(indices) != 0 {
		indices_size := cast(vk.DeviceSize)(size_of(indices[0]) * len(indices))
		index_buffer := create_buffer({.Index}, indices_size, raw_data(indices), loc)
		mesh.ebo = index_buffer
		mesh.index_count = len(indices)
	} else {
		mesh.ebo = nil
	}

	return mesh
}

destroy_mesh :: proc(mesh: ^Mesh, loc := #caller_location) {
	assert_not_nil(mesh)

	destroy_buffer(mesh.vbo)
	ebo, has_ebo := mesh.ebo.?
	if has_ebo {
		destroy_buffer(ebo)
	}
}

draw_mesh :: proc(
	mesh: ^Mesh,
	pipeline: Graphics_Pipeline,
	trf: Maybe(mat4) = nil,
	handles: Handles = {},
	instance_count: u32 = 1,
	loc := #caller_location,
) {
	assert_not_nil(mesh, loc)

	ebo, has_ebo := mesh.ebo.?

	cmd_bind_vertex_buffer(mesh.vbo, 0, loc = loc)
	if has_ebo {
		cmd_bind_index_buffer(ebo, loc = loc)
	}

	layout := cmd_bind_graphics_pipeline(pipeline, loc)

	consts := _get_push_constants_data(trf, handles)
	cmd_push_constants(layout, &consts)

	if has_ebo {
		cmd_draw_indexed(mesh.index_count, instance_count)
	} else {
		cmd_draw(mesh.vertex_count, instance_count)
	}
}

@(private)
_get_push_constants_data :: proc(trf: Maybe(mat4), handles: Handles, loc := #caller_location) -> Push_Constants_Data {
	INVALID_HANDLE :: max(u32)

	consts_data := Push_Constants_Data {
		camera = ctx.gfx.frame.camera.index,
	}

	trf, has_trf := trf.?
	if has_trf {
		consts_data.model = trf
	}

	resource_to_index :: proc(r: Resource_Handle) -> u32 {
		switch h in r {
		case Uniform_Buffer:
			b := ubo_get_buffer(h)
			return b.index if _has_buffer_h(b) else INVALID_HANDLE
		case Storage_Buffer:
			b := sbo_get_buffer(h)
			return b.index if _has_buffer_h(b) else INVALID_HANDLE
		case Buffer:
			return h.index if _has_buffer_h(h) else INVALID_HANDLE
		case Texture:
			return h.index if _has_texture_h(h) else INVALID_HANDLE
		}
		return INVALID_HANDLE
	}

	consts_data.handles[0] = resource_to_index(handles.h0)
	consts_data.handles[1] = resource_to_index(handles.h1)
	consts_data.handles[2] = resource_to_index(handles.h2)
	consts_data.handles[3] = resource_to_index(handles.h3)
	consts_data.handles[4] = resource_to_index(handles.h4)
	consts_data.handles[5] = resource_to_index(handles.h5)
	consts_data.handles[6] = resource_to_index(handles.h6)
	consts_data.handles[7] = resource_to_index(handles.h7)
	consts_data.handles[8] = resource_to_index(handles.h8)
	consts_data.handles[9] = resource_to_index(handles.h9)

	return consts_data
}


// ███████╗██╗    ██╗ █████╗ ██████╗      ██████╗██╗  ██╗ █████╗ ██╗███╗   ██╗
// ██╔════╝██║    ██║██╔══██╗██╔══██╗    ██╔════╝██║  ██║██╔══██╗██║████╗  ██║
// ███████╗██║ █╗ ██║███████║██████╔╝    ██║     ███████║███████║██║██╔██╗ ██║
// ╚════██║██║███╗██║██╔══██║██╔═══╝     ██║     ██╔══██║██╔══██║██║██║╚██╗██║
// ███████║╚███╔███╔╝██║  ██║██║         ╚██████╗██║  ██║██║  ██║██║██║ ╚████║
// ╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝          ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝

@(private)
_init_swapchain :: proc(sample_count: Sample_Count_Flag) {
	ctx.gfx.swapchain = _swapchain_new(sample_count)
	sc := begin_single_cmd()
	_swapchain_setup(ctx.gfx.swapchain, sc.cmd)
	end_single_cmd(sc)
}

@(private)
_destroy_swapchain :: proc() {
	_swapchain_destroy(ctx.gfx.swapchain)
}

@(private)
_recreate_swapchain :: proc() {
	_swapchain_recreate(ctx.gfx.swapchain)
}

@(private)
_swapchaint_get_color_attachment_info :: proc(clear_color: vec4) -> vk.RenderingAttachmentInfo {
	vk_clear_color := vk.ClearValue {
		color = {float32 = clear_color},
	}

	color_attachment_info := vk.RenderingAttachmentInfo {
		sType              = .RENDERING_ATTACHMENT_INFO,
		pNext              = nil,
		imageLayout        = .ATTACHMENT_OPTIMAL,
		resolveImageLayout = .COLOR_ATTACHMENT_OPTIMAL,
		loadOp             = .CLEAR,
		storeOp            = .STORE,
		clearValue         = vk_clear_color,
	}

	msaa_color_texture, has_msaa_color := ctx.gfx.swapchain.msaa_color_texture.?

	if has_msaa_color {
		color_attachment_info.imageView = msaa_color_texture.view
		color_attachment_info.resolveImageView = ctx.gfx.swapchain.image_views[ctx.gfx.swapchain.image_index]
		color_attachment_info.resolveMode = {.AVERAGE_KHR}
	} else {
		color_attachment_info.imageView = ctx.gfx.swapchain.image_views[ctx.gfx.swapchain.image_index]}

	return color_attachment_info
}

@(private = "file")
@(require_results)
_swapchain_new :: proc(sample_count: Sample_Count_Flag) -> ^Swapchain {
	indices := _find_queue_families(ctx.gfx.vk_state.physical_device, ctx.gfx.vk_state.surface)

	surface_format := ctx.gfx.swapchain_cfg.vk_surface_format
	present_mode := ctx.gfx.swapchain_cfg.present_mode
	capabilities := _get_swapchaint_capabilites()
	extent := _choose_swapchain_extent(ctx.window.id, capabilities)

	image_count := capabilities.minImageCount + 1
	if capabilities.maxImageCount > 0 && image_count > capabilities.maxImageCount {
		image_count = capabilities.maxImageCount
	}

	create_info := vk.SwapchainCreateInfoKHR {
		sType            = .SWAPCHAIN_CREATE_INFO_KHR,
		surface          = ctx.gfx.vk_state.surface,
		minImageCount    = image_count,
		imageFormat      = surface_format.format,
		imageColorSpace  = surface_format.colorSpace,
		imageExtent      = extent,
		imageArrayLayers = 1,
		imageUsage       = {.COLOR_ATTACHMENT},
		preTransform     = capabilities.currentTransform,
		compositeAlpha   = {.OPAQUE},
		presentMode      = present_mode,
		clipped          = true,
	}

	if indices.graphics != indices.present {
		create_info.imageSharingMode = .CONCURRENT
		create_info.queueFamilyIndexCount = 2
		create_info.pQueueFamilyIndices = raw_data([]u32{indices.graphics.?, indices.present.?})
	}

	vk_swapchain: vk.SwapchainKHR
	must(vk.CreateSwapchainKHR(ctx.gfx.vk_state.device, &create_info, nil, &vk_swapchain))

	swapchain := new(Swapchain)
	swapchain.swapchain = vk_swapchain
	swapchain.color_format = _vk_to_format(surface_format.format)
	swapchain.width = cast(int)extent.width
	swapchain.height = cast(int)extent.height
	swapchain.sample_count = sample_count
	_swapchain_setup_images(swapchain)
	_swapchain_setup_semaphores(swapchain)

	return swapchain
}

@(private = "file")
_swapchain_setup :: proc(swapchain: ^Swapchain, command_buffer: vk.CommandBuffer) {
	if swapchain.sample_count != ._1 {
		_swapchain_setup_msaa_color_texture(swapchain)
	}

	if .Depth in ctx.info.gfx.attachments {
		stencil := .Stencil in ctx.info.gfx.attachments
		_swapchain_setupt_depth_texture(swapchain, command_buffer, stencil)
	}
}

@(private = "file")
_swapchain_recreate :: proc(swapchain: ^Swapchain) {
	vk.DeviceWaitIdle(ctx.gfx.vk_state.device)

	_swapchain_destroy(swapchain)

	swapchain := _swapchain_new(swapchain.sample_count)

	sc := begin_single_cmd()
	_swapchain_setup(swapchain, sc.cmd)
	end_single_cmd(sc)
}

@(private = "file")
_swapchain_destroy :: proc(swapchain: ^Swapchain) {
	msaa_color_texture, has_color_texture := swapchain.msaa_color_texture.?
	if has_color_texture {
		_destroy_texture(&msaa_color_texture)
	}

	if .Depth in ctx.info.gfx.attachments {
		_destroy_texture(&swapchain.depth_image)
	}

	for sem in swapchain.render_finished_semaphores {
		vk.DestroySemaphore(ctx.gfx.vk_state.device, sem, nil)
	}
	delete(swapchain.render_finished_semaphores)

	for view in swapchain.image_views {
		vk.DestroyImageView(ctx.gfx.vk_state.device, view, nil)
	}

	delete(swapchain.image_views)
	delete(swapchain.images)

	vk.DestroySwapchainKHR(ctx.gfx.vk_state.device, swapchain.swapchain, nil)

	free(swapchain)
}

@(private)
_get_swapchaint_capabilites :: proc() -> (capabilities: vk.SurfaceCapabilitiesKHR) {
	device, vk_render_target := ctx.gfx.vk_state.physical_device, ctx.gfx.vk_state.surface
	must(vk.GetPhysicalDeviceSurfaceCapabilitiesKHR(device, vk_render_target, &capabilities))

	return
}

@(private = "file")
_swapchain_setup_msaa_color_texture :: proc(swapchain: ^Swapchain) {
	color_format := swapchain.color_format

	image, allocation, allocation_info := _create_vk_image(
		cast(u32)swapchain.width,
		cast(u32)swapchain.height,
		1,
		swapchain.sample_count,
		_format_to_vk(color_format),
		vk.ImageTiling.OPTIMAL,
		vk.ImageUsageFlags{.TRANSIENT_ATTACHMENT, .COLOR_ATTACHMENT},
		vma.MemoryUsage.AUTO_PREFER_DEVICE,
		vma.AllocationCreateFlags{},
	)

	view := _create_vk_image_view(image, _format_to_vk(color_format), {.COLOR}, 1)

	texture := Texture_Data {
		id              = image,
		// debug_name      = "swapchain_msaa_color_texture", // FIXME:
		format          = color_format,
		view            = view,
		allocation      = allocation,
		allocation_info = allocation_info,
	}

	swapchain.msaa_color_texture = texture

	s := begin_single_cmd()
	_cmd_image_transition_layout(s.cmd, texture.id, .UNDEFINED, .COLOR_ATTACHMENT_OPTIMAL)
	end_single_cmd(s)
}

@(private = "file")
_swapchain_setupt_depth_texture :: proc(swapchain: ^Swapchain, command_buffer: vk.CommandBuffer, stencil: bool) {
	assert(.Depth in ctx.info.gfx.attachments)

	format: Format
	if stencil {
		format = ctx.gfx.swapchain_cfg.depth_stencil_format
	} else {
		format = ctx.gfx.swapchain_cfg.depth_format
	}

	image, allocation, allocation_info := _create_vk_image(
		cast(u32)swapchain.width,
		cast(u32)swapchain.height,
		1,
		swapchain.sample_count,
		_format_to_vk(format),
		vk.ImageTiling.OPTIMAL,
		vk.ImageUsageFlags{.DEPTH_STENCIL_ATTACHMENT},
		vma.MemoryUsage.AUTO_PREFER_DEVICE,
		vma.AllocationCreateFlags{},
	)

	aspect: vk.ImageAspectFlags = {.DEPTH, .STENCIL} if stencil else {.DEPTH}
	_cmd_image_transition_layout(
		command_buffer,
		image,
		.UNDEFINED,
		.DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
		vk.ImageSubresourceRange{aspectMask = aspect, levelCount = 1, layerCount = 1},
	)

	view := _create_vk_image_view(image, _format_to_vk(format), aspect, 1)
	swapchain.depth_image = Texture_Data {
		id              = image,
		format          = format,
		view            = view,
		allocation      = allocation,
		allocation_info = allocation_info,
	}
}

@(private = "file")
_swapchain_setup_images :: proc(swapchain: ^Swapchain) {
	swapchain.image_index = 0

	count: u32
	must(vk.GetSwapchainImagesKHR(ctx.gfx.vk_state.device, swapchain.swapchain, &count, nil))

	swapchain.images = make([]vk.Image, count)
	swapchain.image_views = make([]vk.ImageView, count)
	must(vk.GetSwapchainImagesKHR(ctx.gfx.vk_state.device, swapchain.swapchain, &count, raw_data(swapchain.images)))

	for image, i in swapchain.images {
		_vk_set_debug_object_name(image, .IMAGE, fmt.tprintf("swapchain image: %d", i))
		swapchain.image_views[i] = _create_vk_image_view(image, _format_to_vk(swapchain.color_format), {.COLOR}, 1)
	}
}

@(private = "file")
_swapchain_setup_semaphores :: proc(swapchain: ^Swapchain) {
	swapchain.render_finished_semaphores = make([]vk.Semaphore, len(swapchain.images))
	sem_info := vk.SemaphoreCreateInfo {
		sType = .SEMAPHORE_CREATE_INFO,
	}
	for _, i in swapchain.images {
		must(vk.CreateSemaphore(ctx.gfx.vk_state.device, &sem_info, nil, &swapchain.render_finished_semaphores[i]))
	}
}

@(private = "file")
@(require_results)
_choose_swapchain_extent :: proc(window: glfw.WindowHandle, capabilities: vk.SurfaceCapabilitiesKHR) -> vk.Extent2D {
	// special value (0xFFFFFFFF, 0xFFFFFFFF) indicating that the surface size will be determined
	// by the extent of a swapchain targeting the surface.
	if capabilities.currentExtent.width != max(u32) {
		return capabilities.currentExtent
	}

	width, height := glfw.GetFramebufferSize(window)
	return vk.Extent2D {
		width = clamp(u32(width), capabilities.minImageExtent.width, capabilities.maxImageExtent.width),
		height = clamp(u32(height), capabilities.minImageExtent.height, capabilities.maxImageExtent.height),
	}
}


// ██████╗ ███████╗███████╗███████╗███████╗██████╗ ███████╗██████╗                     
// ██╔══██╗██╔════╝██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝██╔══██╗                    
// ██║  ██║█████╗  █████╗  █████╗  █████╗  ██████╔╝█████╗  ██║  ██║                    
// ██║  ██║██╔══╝  ██╔══╝  ██╔══╝  ██╔══╝  ██╔══██╗██╔══╝  ██║  ██║                    
// ██████╔╝███████╗██║     ██║     ███████╗██║  ██║███████╗██████╔╝                    
// ╚═════╝ ╚══════╝╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝╚═════╝                     
//
// ██████╗ ███████╗███████╗████████╗██████╗ ██╗   ██╗ ██████╗████████╗ ██████╗ ██████╗ 
// ██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔══██╗██║   ██║██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗
// ██║  ██║█████╗  ███████╗   ██║   ██████╔╝██║   ██║██║        ██║   ██║   ██║██████╔╝
// ██║  ██║██╔══╝  ╚════██║   ██║   ██╔══██╗██║   ██║██║        ██║   ██║   ██║██╔══██╗
// ██████╔╝███████╗███████║   ██║   ██║  ██║╚██████╔╝╚██████╗   ██║   ╚██████╔╝██║  ██║
// ╚═════╝ ╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝

@(private)
_init_deffered_destructor :: proc() {
	ctx.gfx.deffered_destructor = new(Deferred_Destructor)
	ctx.gfx.deffered_destructor.next_index = 0
}

@(private)
_deffered_destructor_add :: proc(resource: Resource) {
	d := ctx.gfx.deffered_destructor
	d.resources[d.next_index] = resource
	d.next_index += 1
	assert(d.next_index < DEFERRED_DESTRUCTOR_SIZE, "Defered destructor is full. Increase DEFERRED_DESTRUCTOR_SIZE.")
}

@(private)
_clear_deffered_destructor :: proc() {
	_deffered_destructor_clear(ctx.gfx.deffered_destructor)
}

@(private)
_destroy_deffered_destructor :: proc() {
	_deffered_destructor_clear(ctx.gfx.deffered_destructor)
	free(ctx.gfx.deffered_destructor)
}

@(private = "file")
_deffered_destructor_clear :: proc(d: ^Deferred_Destructor) {
	for i in 0 ..< d.next_index {
		switch &resource in d.resources[i] {
		case Buffer_Data:
			_destroy_buffer(&resource)
		case Buffer:
			destroy_buffer(resource)
		case Texture_Data:
			_destroy_texture(&resource)
		case Texture:
			t := _acquire_texture_h(resource)
			_destroy_texture(&t)
		}
	}
	d.next_index = 0
}


// ██████╗ ███████╗███████╗ ██████╗██████╗ ██╗██████╗ ████████╗ ██████╗ ██████╗ 
// ██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
// ██║  ██║█████╗  ███████╗██║     ██████╔╝██║██████╔╝   ██║   ██║   ██║██████╔╝
// ██║  ██║██╔══╝  ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║   ██║   ██║██╔══██╗
// ██████╔╝███████╗███████║╚██████╗██║  ██║██║██║        ██║   ╚██████╔╝██║  ██║
// ╚═════╝ ╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝    ╚═════╝ ╚═╝  ╚═╝
//
// ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗                
// ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗               
// ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝               
// ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗               
// ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║               
// ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝               


Pipeline_Layout_Info :: struct {
	layout_infos:  Pipeline_Set_Layout_Infos,
	push_constant: Maybe(Push_Constant_Range),
}

Descriptor_Layout_Manager :: struct {
	layouts:           map[Pipeline_Set_Layout_Info]vk.DescriptorSetLayout,
	pipeline_layoutes: map[Pipeline_Layout_Info]Pipeline_Layout,
}

@(private)
_destroy_descriptor_layout_manager :: proc() {
	for k, layout in ctx.gfx.descriptor_layout_manager.layouts {
		vk.DestroyDescriptorSetLayout(ctx.gfx.vk_state.device, layout, nil)
	}

	for k, pipeline_layout in ctx.gfx.descriptor_layout_manager.pipeline_layoutes {
		vk.DestroyPipelineLayout(ctx.gfx.vk_state.device, pipeline_layout, nil)
	}

	delete(ctx.gfx.descriptor_layout_manager.layouts)
	delete(ctx.gfx.descriptor_layout_manager.pipeline_layoutes)
}

@(require_results)
get_descriptor_set_layouts :: proc(infos: Pipeline_Set_Layout_Infos) -> (layouts: Descriptor_Set_Layouts) {
	for i in 0 ..< infos.len {
		sm.push(&layouts, get_descriptor_set_layout(infos.data[i]))
	}

	return
}

@(require_results)
get_descriptor_set_layout :: proc(info: Pipeline_Set_Layout_Info) -> vk.DescriptorSetLayout {
	layout, ok := ctx.gfx.descriptor_layout_manager.layouts[info]
	if ok do return layout

	layout = _set_info_to_descriptor_set_layout(info)
	ctx.gfx.descriptor_layout_manager.layouts[info] = layout

	return layout
}

@(require_results)
@(private)
_get_pipeline_layout :: proc(info: Pipeline_Layout_Info) -> Pipeline_Layout {
	pipeline_layout, ok := ctx.gfx.descriptor_layout_manager.pipeline_layoutes[info]
	if ok do return pipeline_layout
	layouts := get_descriptor_set_layouts(info.layout_infos)

	pipeline_layout = _create_pipeline_layout(layouts, info.push_constant)
	ctx.gfx.descriptor_layout_manager.pipeline_layoutes[info] = pipeline_layout

	return pipeline_layout
}

@(private = "file")
@(require_results)
_set_info_to_descriptor_set_layout :: proc(set_info: Pipeline_Set_Layout_Info) -> vk.DescriptorSetLayout {
	descriptor_bindings: sm.Small_Array(MAX_PIPELINE_BINDING_COUNT, vk.DescriptorSetLayoutBinding)
	flags_array: sm.Small_Array(MAX_PIPELINE_BINDING_COUNT, vk.DescriptorBindingFlags)

	use_binding_flags := false

	for i in 0 ..< set_info.binding_infos.len {
		binding := set_info.binding_infos.data[i]
		sm.push(
			&descriptor_bindings,
			vk.DescriptorSetLayoutBinding {
				binding = binding.binding,
				descriptorType = binding.descriptor_type,
				descriptorCount = binding.descriptor_count,
				stageFlags = binding.stage_flags,
				pImmutableSamplers = nil,
			},
		)

		flags, has_flags := binding.flags.?
		if has_flags {
			use_binding_flags = true
			sm.push(&flags_array, flags)
		} else {
			sm.push(&flags_array, vk.DescriptorBindingFlags{})
		}
	}

	p_binding_flags: ^vk.DescriptorSetLayoutBindingFlagsCreateInfo = nil

	if use_binding_flags {
		binding_flags := vk.DescriptorSetLayoutBindingFlagsCreateInfo {
			sType         = .DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO,
			pNext         = nil,
			pBindingFlags = raw_data(sm.slice(&flags_array)),
			bindingCount  = cast(u32)flags_array.len,
		}
		p_binding_flags = &binding_flags
	}

	descriptor_set_layout := vk.DescriptorSetLayout{}

	layout_info := vk.DescriptorSetLayoutCreateInfo {
		sType        = .DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
		pNext        = p_binding_flags,
		bindingCount = cast(u32)descriptor_bindings.len,
		pBindings    = raw_data(sm.slice(&descriptor_bindings)),
		flags        = {.UPDATE_AFTER_BIND_POOL},
	}

	must(
		vk.CreateDescriptorSetLayout(ctx.gfx.vk_state.device, &layout_info, nil, &descriptor_set_layout),
		"failed to create descriptor set layout!",
	)

	return descriptor_set_layout
}

@(private = "file")
@(require_results)
_create_pipeline_layout :: proc(
	descriptor_set_layouts: Descriptor_Set_Layouts,
	push_constant: Maybe(vk.PushConstantRange) = nil,
) -> Pipeline_Layout {
	descriptor_set_layouts := descriptor_set_layouts
	push, has_push := push_constant.?

	pipeline_layout_info := vk.PipelineLayoutCreateInfo {
		sType                  = .PIPELINE_LAYOUT_CREATE_INFO,
		setLayoutCount         = cast(u32)descriptor_set_layouts.len,
		pSetLayouts            = raw_data(sm.slice(&descriptor_set_layouts)),
		pushConstantRangeCount = 1 if has_push else 0,
		pPushConstantRanges    = &push,
	}
	layout := Pipeline_Layout{}
	must(vk.CreatePipelineLayout(ctx.gfx.vk_state.device, &pipeline_layout_info, nil, &layout))

	return layout
}

@(private = "file")
_destroy_descriptor_set_layout :: proc(descriptor_set_layout: vk.DescriptorSetLayout) {
	vk.DestroyDescriptorSetLayout(ctx.gfx.vk_state.device, descriptor_set_layout, nil)
}

// ██████╗ ██████╗ ██╗███╗   ███╗██╗████████╗██╗██╗   ██╗███████╗
// ██╔══██╗██╔══██╗██║████╗ ████║██║╚══██╔══╝██║██║   ██║██╔════╝
// ██████╔╝██████╔╝██║██╔████╔██║██║   ██║   ██║██║   ██║█████╗  
// ██╔═══╝ ██╔══██╗██║██║╚██╔╝██║██║   ██║   ██║╚██╗ ██╔╝██╔══╝  
// ██║     ██║  ██║██║██║ ╚═╝ ██║██║   ██║   ██║ ╚████╔╝ ███████╗
// ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝

create_primitive_square :: proc(size: f32 = 1) -> Mesh {
	vertices := [?]Vertex {
		{{size, size, 0.0}, {1, 1}, {0.0, 0.0, -1.0}},
		{{size, -size, 0.0}, {1, 0.0}, {0.0, 0.0, -1.0}},
		{{-size, -size, 0.0}, {0.0, 0.0}, {0.0, 0.0, -1.0}},
		{{size, size, 0.0}, {1, 1}, {0.0, 0.0, -1.0}},
		{{-size, -size, 0}, {0.0, 0.0}, {0.0, 0.0, -1.0}},
		{{-size, size, 0.0}, {0.0, 1}, {0.0, 0.0, -1.0}},
	}

	return create_mesh(vertices[:], {})
}

create_primitive_cube :: proc(size: f32 = 1) -> Mesh {
	vertices := [?]Vertex {
		// position         tex_pos        normal              color
		// -Z
		{{size, size, -size}, {1.0, 1.0}, {0.0, 0.0, -1.0}},
		{{size, -size, -size}, {1.0, 0.0}, {0.0, 0.0, -1.0}},
		{{-size, -size, -size}, {0.0, 0.0}, {0.0, 0.0, -1.0}},
		{{-size, -size, -size}, {0.0, 0.0}, {0.0, 0.0, -1.0}},
		{{-size, size, -size}, {0.0, 1.0}, {0.0, 0.0, -1.0}},
		{{size, size, -size}, {1.0, 1.0}, {0.0, 0.0, -1.0}},

		// +Z
		{{size, -size, size}, {1.0, 0.0}, {0.0, 0.0, 1.0}},
		{{size, size, size}, {1.0, 1.0}, {0.0, 0.0, 1.0}},
		{{-size, -size, size}, {0.0, 0.0}, {0.0, 0.0, 1.0}},
		{{-size, -size, size}, {0.0, 0.0}, {0.0, 0.0, 1.0}},
		{{size, size, size}, {1.0, 1.0}, {0.0, 0.0, 1.0}},
		{{-size, size, size}, {0.0, 1.0}, {0.0, 0.0, 1.0}},

		// -X
		{{-size, -size, -size}, {0.0, 0.0}, {-1.0, 0.0, 0.0}},
		{{-size, -size, size}, {1.0, 0.0}, {-1.0, 0.0, 0.0}},
		{{-size, size, size}, {1.0, 1.0}, {-1.0, 0.0, 0.0}},
		{{-size, size, size}, {1.0, 1.0}, {-1.0, 0.0, 0.0}},
		{{-size, size, -size}, {0.0, 1.0}, {-1.0, 0.0, 0.0}},
		{{-size, -size, -size}, {0.0, 0.0}, {-1.0, 0.0, 0.0}},

		// +X
		{{size, size, size}, {1.0, 1.0}, {1.0, 0.0, 0.0}},
		{{size, -size, size}, {1.0, 0.0}, {1.0, 0.0, 0.0}},
		{{size, -size, -size}, {0.0, 0.0}, {1.0, 0.0, 0.0}},
		{{size, -size, -size}, {0.0, 0.0}, {1.0, 0.0, 0.0}},
		{{size, size, -size}, {0.0, 1.0}, {1.0, 0.0, 0.0}},
		{{size, size, size}, {1.0, 1.0}, {1.0, 0.0, 0.0}},

		// -Y
		{{-size, -size, -size}, {0.0, 1.0}, {0.0, -1.0, 0.0}},
		{{size, -size, -size}, {1.0, 1.0}, {0.0, -1.0, 0.0}},
		{{size, -size, size}, {1.0, 0.0}, {0.0, -1.0, 0.0}},
		{{size, -size, size}, {1.0, 0.0}, {0.0, -1.0, 0.0}},
		{{-size, -size, size}, {0.0, 0.0}, {0.0, -1.0, 0.0}},
		{{-size, -size, -size}, {0.0, 1.0}, {0.0, -1.0, 0.0}},

		// +Y
		{{size, size, size}, {1.0, 0.0}, {0.0, 1.0, 0.0}},
		{{size, size, -size}, {1.0, 1.0}, {0.0, 1.0, 0.0}},
		{{-size, size, -size}, {0.0, 1.0}, {0.0, 1.0, 0.0}},
		{{-size, size, -size}, {0.0, 1.0}, {0.0, 1.0, 0.0}},
		{{-size, size, size}, {0.0, 0.0}, {0.0, 1.0, 0.0}},
		{{size, size, size}, {1.0, 0.0}, {0.0, 1.0, 0.0}},
	}
	return create_mesh(vertices[:], {})
}
