#version 450

#include "gen_types.h"

layout(local_size_x_id = 0) in;

#define getSBO() getMtrlDeltaTimeInfoUBO().sbo
#define getDTime() getMtrlDeltaTimeInfoUBO().delta_time
#define getParticles() getParticleSBO(getSBO()).particles
#define getParticle(index) getParticles()[index]

void main() {
	uint index = gl_GlobalInvocationID.x;

	Particle particle = getParticle(index);
	particle.position = particle.position + particle.velocity.xy * getDTime();
	particle.velocity = particle.velocity;

	// Flip movement at window border
	if ((particle.position.x <= -1.0) || (particle.position.x >= 1.0)) {
		particle.velocity.x = -particle.velocity.x;
	}
	if ((particle.position.y <= -1.0) || (particle.position.y >= 1.0)) {
		particle.velocity.y = -particle.velocity.y;
	}

	particle.velocity -= particle.velocity * 0.1 * getDTime();

	getParticle(index) = particle;
}
