#+private
package shadertypegen

import "core:fmt"
import "core:log"
import "core:odin/ast"
import "core:odin/parser"
import "core:odin/tokenizer"
import "core:os"
import "core:path/filepath"
import "core:slice"
import "core:strconv"
import "core:strings"

WARNING :: "Do not edit this file! It was automatically generated."

Field_Type :: enum {
	None,
	Int,
	Bool,
	Float,
	Vector2,
	Vector3,
	Vector4,
	Mat4,
	Texture,
	Buffer,
	Array,
	Custom,
}

Memory_Layout :: enum {
	Std140,
	Std430,
}

Access_Specifier :: enum {
	Read_Write,
	Readonly,
	Writeonly,
}

Struct_Type :: enum {
	None,
	Material,
	Uniform_Buffer,
	Storage_Buffer,
}

Array_Field :: struct {
	length:              int,
	element_type:        Field_Type,
	element_type_string: string,
}

Field :: struct {
	name:        string,
	type:        Field_Type,
	type_string: string,
	array:       Array_Field,
}

Struct :: struct {
	name:             string,
	type:             Struct_Type,
	fields:           []Field,
	path:             string,
	err:              string,
	memory_layout:    Memory_Layout,
	access_specifier: Access_Specifier,
}

Ve_Package_Info :: struct {
	alias: string,
	path:  string,
}

Parse_Data :: struct {
	structures: map[string]Struct,
	ordered:    [dynamic]string,
}

memroy_layout_to_string :: proc(layout: Memory_Layout) -> string {return "std140" if layout == .Std140 else "std430"}
get_odin_conv_proc_name :: proc(name: string, memory_layout: Memory_Layout) -> string {
	return fmt.aprintf("conv_%s_to_data_%s", strings.to_lower(name), memroy_layout_to_string(memory_layout))
}
get_odin_conv_array_proc_name :: proc(name: string, memory_layout: Memory_Layout) -> string {
	return fmt.aprintf("conv_%s_array_to_data_%s", strings.to_lower(name), memroy_layout_to_string(memory_layout))
}
get_odin_data_struct_name :: proc(name: string, memory_layout: Memory_Layout) -> string {
	return fmt.aprintf("%s_%s", memroy_layout_to_string(memory_layout), name)
}
get_odin_proc_struct_name :: proc(s: Struct) -> string {
	name: string
	switch s.type {
	case .None:
		name = s.name
	case .Material:
		name = remove_struct_suffix(s.name, "material")
	case .Uniform_Buffer:
		name = remove_struct_suffix(s.name, "ubo")
	case .Storage_Buffer:
		name = remove_struct_suffix(s.name, "sbo")
	}
	name = strings.trim(name, "_")
	name = strings.trim_space(name)
	return name
}
get_odin_buffer_handle_get_proc_name :: proc(s: Struct) -> string {
	switch s.type {
	case .None:
		return "None"
	case .Material:
		return "None"
	case .Uniform_Buffer:
		return "get_uniform_buffer"
	case .Storage_Buffer:
		return "get_storage_buffer"
	}
	return "None"
}
get_odin_buffer_handle_type_name :: proc(s: Struct) -> string {
	switch s.type {
	case .None:
		return "None"
	case .Material:
		return "Material"
	case .Uniform_Buffer:
		return "Uniform_Buffer"
	case .Storage_Buffer:
		return "Storage_Buffer"
	}
	return "None"
}
get_odin_buffer_type_name :: proc(s: Struct) -> string {
	switch s.type {
	case .None:
		return "None"
	case .Material:
		return "Material"
	case .Uniform_Buffer:
		return "Uniform_Buffer_Data"
	case .Storage_Buffer:
		return "Uniform_Buffer_Data"
	}
	return "None"
}
get_odin_proc_struct_prefix :: proc(s: Struct) -> string {
	switch s.type {
	case .None:
		return ""
	case .Material:
		return "mtrl"
	case .Uniform_Buffer:
		return "ubo"
	case .Storage_Buffer:
		return "sbo"
	}
	return ""
}

get_glsl_struct_name :: proc(name: string) -> string {
	glsl_struct_name, _ := strings.replace_all(name, "_", "")
	return glsl_struct_name
}

generate_glsl :: proc(store: Parse_Data, path: string, package_name: string, loc := #caller_location) -> bool {
	f, ok := os.open(path, os.O_WRONLY | os.O_CREATE | os.O_TRUNC, 0o644)
	defer os.close(f)

	if ok != nil {
		log.errorf("Failed opening '%s' folder", path)
		return false
	}

	fmt.fprintfln(f, "// %s\n", WARNING)
	fmt.fprintfln(f, "#ifndef {0:s}\n#define {0:s}\n", fmt.aprintf("GEN_TYPES_%s_H", strings.to_upper(package_name)))
	fmt.fprintln(f, "#include \"buildin:base/bindless.h\"\n")

	for name in store.ordered {
		s := store.structures[name]

		switch s.type {
		case .Material:
			fmt.fprintfln(f, "// {0:s}", s.name)

			glsl_struct_name := get_glsl_struct_name(s.name)
			fmt.fprintfln(f, "RegisterUniform(%s, {{", glsl_struct_name)

			for field in s.fields {
				assert(field.type != .None)
				fmt.fprintfln(f, "	%s %s;", field_to_glsl_type(field), field.name)
			}

			fmt.fprintfln(f, "}});\n")

			func_name, r_ok := strings.replace_all(glsl_struct_name, "Material", "")
			fmt.fprintfln(
				f,
				"#define getMtrl{1:s}() GetResource({0:s}, PushConstants.material)",
				glsl_struct_name,
				func_name,
			)
			fmt.fprintfln(f, "\n")
		case .Uniform_Buffer:
			fmt.fprintfln(f, "// {0:s}", s.name)

			glsl_struct_name := get_glsl_struct_name(s.name)
			fmt.fprintfln(f, "RegisterUniform(%s, {{", glsl_struct_name)

			for field in s.fields {
				assert(field.type != .None)
				fmt.fprintfln(f, "	%s %s;", field_to_glsl_type(field), field.name)
			}

			fmt.fprintfln(f, "}});\n")

			func_name, r_ok := strings.replace_all(glsl_struct_name, "Ubo", "")
			func_name, r_ok = strings.replace_all(func_name, "UBO", "")

			fmt.fprintfln(f, "#define get{1:s}UBO(handle) GetResource({0:s}, handle)", glsl_struct_name, func_name)
			fmt.fprintfln(f, "\n")
		case .Storage_Buffer:
			fmt.fprintfln(f, "// {0:s}", s.name)

			glsl_struct_name := get_glsl_struct_name(s.name)
			access: string
			switch s.access_specifier {
			case .Read_Write:
				access = ""
			case .Readonly:
				access = "readonly"
			case .Writeonly:
				access = "writeonly"
			}

			fmt.fprintfln(
				f,
				"RegisterBuffer({0:s}, {1:s}, {2:s}, {{",
				"std140" if s.memory_layout == .Std140 else "std430",
				access,
				glsl_struct_name,
			)

			for field in s.fields {
				assert(field.type != .None)
				fmt.fprintfln(f, "	%s %s;", field_to_glsl_type(field), field.name)
			}

			fmt.fprintfln(f, "}});\n")

			func_name, r_ok := strings.replace_all(glsl_struct_name, "Sbo", "")
			func_name, r_ok = strings.replace_all(func_name, "SBO", "")

			fmt.fprintfln(f, "#define get{1:s}SBO(handle) GetResource({0:s}, handle)", glsl_struct_name, func_name)
			fmt.fprintfln(f, "\n")
		case .None:
			fmt.fprintfln(f, "// {0:s}", s.name)

			glsl_struct_name := get_glsl_struct_name(s.name)
			fmt.fprintfln(f, "struct %s {{", glsl_struct_name)

			for field in s.fields {
				assert(field.type != .None)
				fmt.fprintfln(f, "	%s %s;", field_to_glsl_type(field), field.name)
			}

			fmt.fprintfln(f, "}};\n")
		}
	}

	fmt.fprint(f, "#endif")

	return true
}

generate_odin :: proc(
	d: Parse_Data,
	path: string,
	package_name: string,
	gfx_pkg_info: Ve_Package_Info,
	loc := #caller_location,
) -> bool {
	f, ok := os.open(path, os.O_WRONLY | os.O_CREATE | os.O_TRUNC, 0o644)
	defer os.close(f)

	if ok != nil {
		log.errorf("Failed opening '%s' folder", path)
		return false
	}

	fmt.fprintfln(f, "// %s\n", WARNING)
	fmt.fprintfln(f, "package %s\n", package_name)
	fmt.fprintfln(f, "import \"core:math/linalg/glsl\"")
	if gfx_pkg_info.path != "" {
		fmt.fprintfln(f, "import {0:s} \"{1:s}\"", gfx_pkg_info.alias, gfx_pkg_info.path)
	}

	pkg_pref := ""
	if gfx_pkg_info.alias != "" {
		pkg_pref = fmt.aprintf("%s.", gfx_pkg_info.alias)
	} else if gfx_pkg_info.path != "" {
		path := strings.split(gfx_pkg_info.path, "/")
		pkg_pref = fmt.aprintf("%s.", path[len(path) - 1])
	}

	fmt.fprintfln(
		f,
		`
ubo_get_buffer :: proc(h: {0:s}Uniform_Buffer) -> {0:s}Buffer{{
	b := {0:s}get_uniform_buffer(h)
	return b.buffer_h
}}
sbo_get_buffer :: proc(h: {0:s}Storage_Buffer) -> {0:s}Buffer{{
	b := {0:s}get_storage_buffer(h)
	return b.buffer_h
}}
	`,
		pkg_pref,
	)


	for name in d.ordered {
		s := d.structures[name]
		switch s.type {
		case .Material:
			generate_odin_material_struct(d, f, s, pkg_pref)
		case .Uniform_Buffer:
			generate_odin_uniform_buffer_struct(d, f, s, pkg_pref)
		case .Storage_Buffer:
			generate_odin_storage_buffer_struct(d, f, s, pkg_pref)
		case .None:
			generate_odin_common_struct(d, f, s, pkg_pref)
		}
	}

	return true
}

generate_odin_common_struct :: proc(d: Parse_Data, f: os.Handle, s: Struct, gfx_pref: string) {
	fmt.fprintfln(f, `
///////////////////////////
// %s
/////////////dependence////
`, s.name)

	memory_layouts := [2]Memory_Layout{.Std140, .Std430}
	for layout in memory_layouts {
		fmt.fprintfln(f, "%s :: struct #packed {{", get_odin_data_struct_name(s.name, layout))

		for field in calculate_padding_by_memeory_layout(layout, d, s.fields) {
			fmt.fprintln(f, get_data_field_for_odin(field, gfx_pref, s.memory_layout))
		}
		fmt.fprintln(f, "}\n")

		fmt.fprintfln(
			f,
			"{0:s} :: proc(dst: ^{2:s}, src: {1:s}, loc := #caller_location) {{",
			get_odin_conv_proc_name(s.name, layout),
			s.name,
			get_odin_data_struct_name(s.name, layout),
		)

		for field in s.fields {
			print_field_to_data_field(f, "src", "dst", field, gfx_pref, s.memory_layout)
		}

		fmt.fprint(f, "\n}")

		fmt.fprintf(
			f,
			`
{0:s} :: proc(dst: []{2:s}, src: []{1:s}, loc := #caller_location) {{
	assert(len(src) == len(dst), "The array size has changed. Please regenerate the code.", loc)
	for _, i in src {{
		{3:s}(&dst[i], src[i])
	}}
	return
}}
`,
			get_odin_conv_array_proc_name(s.name, layout),
			s.name,
			get_odin_data_struct_name(s.name, layout),
			get_odin_conv_proc_name(s.name, layout),
		)

		fmt.fprint(f, "\n")
	}
}

generate_odin_material_struct :: proc(d: Parse_Data, f: os.Handle, s: Struct, gfx_pref: string) {
	fmt.fprintfln(f, `
///////////////////////////
// %s
//////////////material/////
`, s.name)
	fmt.fprintfln(f, "%s :: struct #packed {{", get_odin_data_struct_name(s.name, s.memory_layout))

	for field in calculate_padding_by_memeory_layout(s.memory_layout, d, s.fields) {
		fmt.fprintln(f, get_data_field_for_odin(field, gfx_pref, s.memory_layout))
	}
	fmt.fprintln(f, "}")

	fmt.fprintfln(
		f,
		`
create_mtrl_{0:s} :: proc(
	pipeline_h: {2:s}Render_Pipeline_Handle,
	buffer_usage: {2:s}Buffer_Usage_Flags = {{.Uniform, .Host_Write}},
	loc := #caller_location
) -> {2:s}Material_Handle {{
	assert(.Uniform in buffer_usage, loc = loc)
	assert(.Host_Write in buffer_usage, loc = loc)
	m := {2:s}Material{{}}
	m.pipeline_h = pipeline_h
	material_data := new({1:s})
	m.data = material_data
	m.type = typeid_of(^{1:s})
	m.dirty = true
	m.apply = mtrl_{0:s}_apply

	m.buffer_h := {2:s}create_buffer(buffer_usage, size_of({3:s}), loc = loc)
`,
		get_odin_proc_struct_name(s),
		s.name,
		gfx_pref,
		get_odin_data_struct_name(s.name, s.memory_layout),
	)

	for field in s.fields {
		default_value, has_default_value := get_field_type_default_value(field.type, gfx_pref).?
		if !has_default_value do continue

		fmt.fprintfln(f, "	material_data.{0:s} = {1:s}", field.name, default_value)
	}

	fmt.fprintfln(f, `
	return {0:s}store_material(m) 
}}`, gfx_pref)

	generate_odin_get_set_proc(f, s, gfx_pref)
	generate_odin_apply_proc(f, s, gfx_pref)
}

generate_odin_get_set_proc :: proc(f: os.Handle, s: Struct, ve_pkg: string) {
	for field in s.fields {
		field := field
		field.array.length = -1
		fmt.fprintf(
			f,
			`
{0:s}_{1:s}_set_{3:s} :: proc(h: {7:s}{5:s}, {3:s}_: {4:s}, loc := #caller_location) {{
	b := {7:s}{6:s}(h, loc)
	assert(b.type == typeid_of(^{2:s}), loc = loc)
	data := cast(^{2:s})b.data
`,
			get_odin_proc_struct_prefix(s),
			get_odin_proc_struct_name(s),
			s.name,
			field.name,
			field_to_odin_type(field, ve_pkg),
			get_odin_buffer_handle_type_name(s),
			get_odin_buffer_handle_get_proc_name(s),
			ve_pkg,
		)

		if field.type == .Array {
			fmt.fprintfln(f, "	assert(len(data.{0:s}[:]) == len({0:s}_), loc = loc)", field.name)
			fmt.fprintfln(f, "	copy_slice(data.{0:s}[:], {0:s}_)", field.name)
		} else {
			fmt.fprintfln(f, "	data.{0:s} = {0:s}_", field.name)
		}

		fmt.fprintf(
			f,
			`	b.dirty = true
}}
{0:s}_{1:s}_get_{3:s} :: proc(h: {7:s}{5:s}, loc := #caller_location) -> {4:s}{{
	b := {7:s}{6:s}(h, loc)
	assert(b.type == typeid_of(^{2:s}), loc = loc)
	data := cast(^{2:s})b.data
`,
			get_odin_proc_struct_prefix(s),
			get_odin_proc_struct_name(s),
			s.name,
			field.name,
			field_to_odin_type(field, ve_pkg),
			get_odin_buffer_handle_type_name(s),
			get_odin_buffer_handle_get_proc_name(s),
			ve_pkg,
		)

		if field.type == .Array {
			fmt.fprintfln(f, "	return data.{0:s}[:]", field.name)
		} else {
			fmt.fprintfln(f, "	return data.{0:s}", field.name)
		}
		fmt.fprintln(f, "}")
	}
}

generate_odin_apply_proc :: proc(f: os.Handle, s: Struct, ve_pkg: string) {
	fmt.fprintf(
		f,
		`
{0:s}_{1:s}_apply :: proc(b: ^{3:s}Cached_Buffer, loc := #caller_location) {{
	assert(b != nil, loc = loc)
	assert(b.type == typeid_of(^{2:s}), loc = loc)
	if !b.dirty do return
	src_data := cast(^{2:s})b.data

	gpu_data_ptr : ^{4:s}
	when size_of({4:s}) < 254 * 1024 {{
		gpu_data := {4:s}{{}}
		gpu_data_ptr = &gpu_data
	}} else {{
		gpu_data_ptr = new({4:s}, context.temp_allocator)
	}}
`,
		get_odin_proc_struct_prefix(s),
		get_odin_proc_struct_name(s),
		s.name,
		ve_pkg,
		get_odin_data_struct_name(s.name, s.memory_layout),
	)

	for field in s.fields {
		print_field_to_data_field(f, "src_data", "gpu_data_ptr", field, ve_pkg, s.memory_layout)
	}

	fmt.fprintf(
		f,
		`
	{1:s}buffer_fill(b.buffer_h, gpu_data_ptr, size_of({0:s}), loc = loc)
	b.dirty = false
}}
`,
		get_odin_data_struct_name(s.name, s.memory_layout),
		ve_pkg,
	)
}

generate_odin_storage_buffer_struct :: proc(d: Parse_Data, f: os.Handle, s: Struct, gfx_pref: string) {
	fmt.fprintfln(f, `
///////////////////////////
// %s
/////////storage_buffer////
`, s.name)

	fmt.fprintfln(f, "%s :: struct #packed {{", get_odin_data_struct_name(s.name, s.memory_layout))

	for field in calculate_padding_by_memeory_layout(s.memory_layout, d, s.fields) {
		fmt.fprintln(f, get_data_field_for_odin(field, gfx_pref, s.memory_layout))
	}
	fmt.fprintln(f, "}")

	fmt.fprintfln(
		f,
		`
create_sbo_{0:s} :: proc(
	buffer_usage: {2:s}Buffer_Usage_Flags = {{.Storage}},
	loc := #caller_location
) -> {2:s}Storage_Buffer {{
	assert(.Storage in buffer_usage, loc = loc)
	s: {2:s}Storage_Buffer_Data
	data := new({1:s})
	s.data = data
	s.type = typeid_of(^{1:s})
	s.dirty = true
	s.apply = sbo_{0:s}_apply

	s.buffer_h = {2:s}create_buffer(buffer_usage, size_of({3:s}), loc = loc)
`,
		get_odin_proc_struct_name(s),
		s.name,
		gfx_pref,
		get_odin_data_struct_name(s.name, s.memory_layout),
	)

	for field in s.fields {
		default_value, has_default_value := get_field_type_default_value(field.type, gfx_pref).?
		if !has_default_value do continue
		fmt.fprintfln(f, "	data.{0:s} = {1:s}", field.name, default_value)
	}

	fmt.fprintfln(f, `
	return {0:s}store_storage_buffer(s)
}}`, gfx_pref)
	generate_odin_get_set_proc(f, s, gfx_pref)
	generate_odin_apply_proc(f, s, gfx_pref)
}

generate_odin_uniform_buffer_struct :: proc(d: Parse_Data, f: os.Handle, s: Struct, gfx_pref: string) {
	fmt.fprintfln(f, `
///////////////////////////
// %s
//////////unform_buffer////
`, s.name)
	fmt.fprintfln(f, "%s :: struct #packed {{", get_odin_data_struct_name(s.name, s.memory_layout))

	for field in calculate_padding_by_memeory_layout(s.memory_layout, d, s.fields) {
		fmt.fprintln(f, get_data_field_for_odin(field, gfx_pref, s.memory_layout))
	}
	fmt.fprintln(f, "}")

	fmt.fprintfln(
		f,
		`
create_ubo_{0:s} :: proc(
	buffer_usage: {2:s}Buffer_Usage_Flags = {{.Uniform, .Host_Write}},
	loc := #caller_location
) -> {2:s}Uniform_Buffer {{
	assert(.Uniform in buffer_usage, loc = loc)
	assert(.Host_Write in buffer_usage, loc = loc)
	u: {2:s}Uniform_Buffer_Data
	uniform_data := new({1:s})
	u.data = uniform_data
	u.type = typeid_of(^{1:s})
	u.dirty = true
	u.apply = ubo_{0:s}_apply

	u.buffer_h = {2:s}create_buffer(buffer_usage, size_of({3:s}), loc = loc)
`,
		get_odin_proc_struct_name(s),
		s.name,
		gfx_pref,
		get_odin_data_struct_name(s.name, s.memory_layout),
	)

	for field in s.fields {
		default_value, has_default_value := get_field_type_default_value(field.type, gfx_pref).?
		if !has_default_value do continue

		fmt.fprintfln(f, "	uniform_data.{0:s} = {1:s}", field.name, default_value)
	}

	fmt.fprintfln(f, `
	return {0:s}store_uniform_buffer(u)
}}`, gfx_pref)

	generate_odin_get_set_proc(f, s, gfx_pref)
	generate_odin_apply_proc(f, s, gfx_pref)
}

print_field_to_data_field :: proc(
	f: os.Handle,
	src_name: string,
	dst_name: string,
	field: Field,
	gfx_pref: string,
	layout: Memory_Layout,
) {
	if (field.type == .Texture) {
		fmt.fprintfln(
			f,
			"	{3:s}.{0:s} = {2:s}.{0:s}.index if {1:s}has_texture_h({2:s}.{0:s}) else max(u32)",
			field.name,
			gfx_pref,
			src_name,
			dst_name,
		)
	} else if (field.type == .Buffer) {
		fmt.fprintfln(
			f,
			"	{3:s}.{0:s} = {2:s}.{0:s}.index if {1:s}has_buffer_h({2:s}.{0:s}) else max(u32)",
			field.name,
			gfx_pref,
			src_name,
			dst_name,
		)
	} else if (field.type == .Custom) {
		fmt.fprintfln(
			f,
			"	{0:s}(&{3:s}.{1:s}, {2:s}.{1:s})",
			get_odin_conv_proc_name(field.type_string, layout),
			field.name,
			src_name,
			dst_name,
		)
	} else if (field.type == .Array && field.array.element_type == .Custom) {
		assert(field.array.length != -1)
		fmt.fprintfln(
			f,
			"	{0:s}({3:s}.{1:s}[:], {2:s}.{1:s}[:])",
			get_odin_conv_array_proc_name(field.array.element_type_string, layout),
			field.name,
			src_name,
			dst_name,
		)
	} else {
		fmt.fprintfln(f, "	{2:s}.{0:s} = {1:s}.{0:s}", field.name, src_name, dst_name)
	}
}

get_field_type_default_value :: proc(field_type: Field_Type, gfx_pref: string) -> Maybe(string) {
	switch field_type {
	case .None, .Int, .Bool, .Float, .Vector2, .Vector3, .Vector4, .Mat4, .Array, .Custom:
		return nil
	case .Texture:
		return fmt.aprintf("%sINVALID_TEXTURE_HANDLE", gfx_pref)
	case .Buffer:
		return fmt.aprintf("%sINVALID_BUFFER_HANDLE", gfx_pref)
	}
	return nil
}

get_data_field_for_odin :: proc(field: Field, gfx_pref: string, layout: Memory_Layout) -> string {
	assert(field.type != .None)
	if field.type == .Texture || field.type == .Buffer {
		return fmt.aprintf("	%s: u32,", field.name)
	} else if field.type == .Custom {
		return fmt.aprintf("	%s: %s,", field.name, get_odin_data_struct_name(field.type_string, layout))
	} else if field.type == .Array && field.array.element_type == .Custom {
		return fmt.aprintf(
			"	%s: %s,",
			field.name,
			field_to_odin_type(
				Field {
					type = .Array,
					array = Array_Field {
						length = field.array.length,
						element_type = .Custom,
						element_type_string = get_odin_data_struct_name(field.array.element_type_string, layout),
					},
				},
				"",
			),
		)
	} else {
		return fmt.aprintf("	%s: %s,", field.name, field_to_odin_type(field, gfx_pref))
	}
}

remove_struct_suffix :: proc(name: string, suffix: string) -> string {
	lower_name := strings.to_lower(name)
	if len(lower_name) >= len(suffix) && lower_name[len(lower_name) - len(suffix):] == suffix {
		return lower_name[:len(lower_name) - len(suffix)]
	}
	return lower_name
}

parse_constns :: proc(pkg: ^ast.Package, loc := #caller_location) -> map[string]int {
	ok: bool
	Const_Value :: union {
		string,
		int,
	}

	name_to_value: map[string]Const_Value

	for path, file in pkg.files {
		for decl in file.decls {
			value_decl: ^ast.Value_Decl
			if value_decl, ok = decl.derived.(^ast.Value_Decl); !ok || len(value_decl.values) < 1 {
				continue
			}

			value := value_decl.values[0]
			ident, i_ok := value_decl.names[0].derived.(^ast.Ident)
			assert(i_ok)

			#partial switch v in value.derived_expr {
			case ^ast.Basic_Lit:
				if v.tok.kind == .Integer {
					name_to_value[ident.name], _ = strconv.parse_int(v.tok.text)
				}
			case ^ast.Ident:
				name_to_value[ident.name] = v.name
			}
		}
	}

	constants: map[string]int

	get_const_value :: proc(name: string, name_to_value: map[string]Const_Value) -> (int, bool) {
		current: string = name
		for i in 0 ..< 100 {
			v, ok := name_to_value[current]
			if !ok do break
			if v_int, vok := v.(int); vok do return v_int, true
			if v_str, sok := v.(string); sok do current = v_str
		}
		return 0, false
	}

	for name, _ in name_to_value {
		if v, ok := get_const_value(name, name_to_value); ok {
			constants[name] = v
		}
	}

	return constants
}

parse_structures :: proc(pkg: ^ast.Package, loc := #caller_location) -> (Parse_Data, bool) {
	ok: bool

	consts := parse_constns(pkg, loc)

	Temp_Data :: struct {
		structures: map[string]Struct,
		refs:       map[string][dynamic]string,
		unresolved: [dynamic]string,
		resolved:   [dynamic]string,
		heads:      [dynamic]string,
	}

	t := Temp_Data{}

	First_Pass_Strcut :: struct {
		ast_struct_type: ^ast.Struct_Type,
		ast_attributes:  []^ast.Attribute,
		name:            string,
		path:            string,
	}
	first_pass := make([dynamic]First_Pass_Strcut)
	available_names := make([dynamic]string)

	get_all_dep :: proc(s: string, t: ^Temp_Data) -> [dynamic]string {
		get_deps :: proc(s: string, t: ^Temp_Data) -> [dynamic]string {
			deps: [dynamic]string
			append(&deps, s)

			r, ok := t.refs[s]
			if !ok do return deps

			for dep_name in r {
				d := get_deps(dep_name, t)
				append(&deps, ..d[:])
			}

			return deps
		}

		r, ok := t.refs[s]
		if !ok do return nil

		deps := make([dynamic]string)
		for dep_name in r {
			d := get_deps(dep_name, t)
			append(&deps, ..d[:])
		}

		return deps
	}

	resolve :: proc(s: string, t: ^Temp_Data) {
		// already resolved
		if slice.contains(t.resolved[:], s) do return

		index, ok := slice.linear_search(t.unresolved[:], s)
		assert(ok)

		unordered_remove(&t.unresolved, index)
		append(&t.resolved, s)

		need_resolve: [dynamic]string
		for us in t.unresolved {
			srefs, ok := t.refs[us]
			if !ok do continue
			unresolved_refs := len(srefs)
			resolved_refs := 0

			for r in srefs {
				for rs in t.resolved {
					if rs == r {
						resolved_refs += 1
					}
				}
			}
			assert(resolved_refs <= unresolved_refs)

			if resolved_refs == unresolved_refs {
				append(&need_resolve, us)
			}
		}

		for r in need_resolve {
			resolve(r, t)
		}
	}

	for path, file in pkg.files {
		for decl in file.decls {
			value_decl: ^ast.Value_Decl
			if value_decl, ok = decl.derived.(^ast.Value_Decl); !ok || len(value_decl.values) < 1 {
				continue
			}

			value := value_decl.values[0]

			ast_struct_type: ^ast.Struct_Type
			if ast_struct_type, ok = value.derived.(^ast.Struct_Type); !ok {
				continue
			}
			if ident, ok := value_decl.names[0].derived.(^ast.Ident); ok {
				append(
					&first_pass,
					First_Pass_Strcut {
						name = ident.name,
						path = path,
						ast_struct_type = ast_struct_type,
						ast_attributes = value_decl.attributes[:],
					},
				)
				append(&available_names, ident.name)
			}
		}
	}

	for sp in first_pass {
		s := Struct{}
		fields := make([dynamic]Field)
		s.name = sp.name
		s.path = sp.path

		for field_prs in sp.ast_struct_type.fields.list {
			field, err := parse_field(field_prs, available_names[:], consts)
			if err != "" {
				s.err = err
				break
			}
			append(&fields, field)
		}

		s.fields = fields[:]
		a_name, a_value, a_pos := get_attribute_data(sp.ast_attributes)
		s.type = get_struct_type(a_name, a_value, a_pos)
		s.memory_layout = get_struct_memory_layout(s.type, a_value)
		s.access_specifier = get_struct_access_specifier(s.type, a_value)
		s.path = sp.path

		add_refs :: proc(p: ^Temp_Data, owner: string, dep: string) {
			if _, ok := p.refs[owner]; !ok {
				p.refs[owner] = make([dynamic]string)
			}
			append(&p.refs[owner], dep)
		}

		for field in fields {
			if field.type == .Custom {
				add_refs(&t, s.name, field.type_string)
			} else if field.type == .Array && field.array.element_type == .Custom {
				add_refs(&t, s.name, field.array.element_type_string)
			}
		}

		has_deps: bool
		for master, slave in t.refs {
			if master == s.name {
				has_deps = true
				break
			}
		}

		t.structures[s.name] = s
		append(&t.unresolved, s.name)

		if !has_deps do append(&t.heads, s.name)
	}

	for h in t.heads do resolve(t.structures[h].name, &t)


	ordered: [dynamic]string

	for name, s in t.structures {
		if s.type == .None do continue
		deps := get_all_dep(name, &t)
		slice.reverse(deps[:])
		for d in deps {
			if slice.contains(ordered[:], d) do continue
			dep_s := &t.structures[d]

			if s.memory_layout == .Std140 {
				for field in s.fields {
					if field.type == .Array && field.array.length == -1 {
						dep_s.err = "Only fixed arrays are supported."
					}
				}
			}
			append(&ordered, d)
		}
		append(&ordered, name)
	}

	failed: bool
	for name in ordered {
		s := t.structures[name]
		if s.type == .None do continue

		SEP :: "----------------------------"

		print_struct_err :: proc(s: Struct) {
			log.errorf(`
Unable process struct: %s (type: %s)
File: %s
ERROR: %s`, s.name, s.type, s.path, s.err)
		}

		if s.err != "" {
			print_struct_err(s)
			log.error(SEP)
			failed = true
		}

		for d in get_all_dep(name, &t) {
			dep := t.structures[d]
			if dep.err != "" {
				print_struct_err(dep)
				log.error(SEP)
				failed = true
			}
		}
	}

	if failed {
		log.error("To view the structure declaration rules, run the program with the -rules flag.")
		return {}, false
	}

	return Parse_Data{ordered = ordered, structures = t.structures}, true
}

get_attribute_data :: proc(attributes: []^ast.Attribute) -> (name: string, value: string, pos: tokenizer.Pos) {
	for attribute in attributes {
		for elem in attribute.elems {
			pos = elem.pos
			ident, ok_ident := elem.derived.(^ast.Ident)
			if ok_ident do name = ident.name

			field_value, ok_field_value := elem.derived.(^ast.Field_Value)
			if ok_field_value {
				field_ident := field_value.field.derived.(^ast.Ident)
				name = field_ident.name

				basic_lit, ok_basic_lit := field_value.value.derived.(^ast.Basic_Lit)
				if ok_basic_lit do value = basic_lit.tok.text
			}
		}
	}

	return
}

get_struct_type :: proc(attribute_name: string, attribute_value: string, pos: tokenizer.Pos) -> Struct_Type {
	if attribute_name == MATERIAL_ATTRIBUTE {
		return .Material
	} else if attribute_name == BUFFER_ATTRIBUTE {
		if attribute_value == "" || strings.contains(attribute_value, BUFFER_ATTRIBUTE_UNIFORM_VALUE) {
			return .Uniform_Buffer
		} else if strings.contains(attribute_value, BUFFER_ATTRIBUTE_STORAGE_VALUE) {
			return .Storage_Buffer
		}
		log.warnf(
			"Invalid attribute value: {2:s}. Expected \"\", \"{0:s}\" or \"{1:s}\"\n{3:#v}",
			BUFFER_ATTRIBUTE_STORAGE_VALUE,
			BUFFER_ATTRIBUTE_UNIFORM_VALUE,
			attribute_value,
			pos,
		)
	}
	return .None
}

get_struct_memory_layout :: proc(struct_type: Struct_Type, attribute_value: string) -> Memory_Layout {
	#partial switch struct_type {
	case .Material:
		return .Std140
	case .Uniform_Buffer:
		return .Std140
	case .Storage_Buffer:
		if strings.contains(attribute_value, "std140") {
			return .Std140
		}
		return .Std430
	}
	return .Std140
}

get_struct_access_specifier :: proc(struct_type: Struct_Type, attribute_value: string) -> Access_Specifier {
	#partial switch struct_type {
	case .Material:
		return .Readonly
	case .Uniform_Buffer:
		return .Readonly
	case .Storage_Buffer:
		if strings.contains(attribute_value, "readonly") {
			return .Readonly
		} else if strings.contains(attribute_value, "writeonly") {
			return .Writeonly
		}
		return .Read_Write
	}
	return .Readonly
}

parse_field :: proc(
	f: ^ast.Field,
	available_struct_name: []string,
	consts: map[string]int,
) -> (
	field: Field,
	err: string,
) {
	field_type, field_type_string := parse_field_type(f.type)
	field_name_expr := f.names[0]
	field_name_expr_ident, ok := field_name_expr.derived.(^ast.Ident)
	assert(ok)

	field.name = field_name_expr_ident.name
	field.type = field_type
	field.type_string = field_type_string

	field_error :: proc(field: Field, err: string) -> string {
		return fmt.aprintf("Unprocessable field \"%s: %s\"\n%s", field.name, field.type_string, err)
	}

	if field.type == .None {
		if !slice.contains(available_struct_name, field.type_string) {
			err = field_error(field, "Type is unprocessible or does not comply with the established rules.")
			return
		}

		field.type = .Custom
		return
	}

	if field.type == .Array {
		ALLOWED_ARRAY_ELEMNT_TYPE := [?]Field_Type{.Vector4, .Mat4}
		array_type, ok_a := f.type.derived.(^ast.Array_Type)
		assert(ok_a)
		element_t, element_t_str := parse_field_type(array_type.elem)
		if element_t == .Array {
			err = field_error(field, "Two-dimensions array not supported.")
			return
		}

		matched := slice.contains(ALLOWED_ARRAY_ELEMNT_TYPE[:], element_t)

		if !matched && slice.contains(available_struct_name, element_t_str) {
			assert(ok)
			element_t = .Custom
			matched = true
		}

		if !matched {
			err = field_error(
				field,
				fmt.aprint("Array element type should be:", ALLOWED_ARRAY_ELEMNT_TYPE, "or user's struct."),
			)
			return
		}

		length: int
		if array_type.len == nil {
			length = -1
		} else {
			#partial switch len in array_type.len.derived {
			case ^ast.Ident:
				length = consts[len.name]
			case:
				unary_expr := cast(^ast.Unary_Expr)array_type.len
				length_text := unary_expr.op.text
				ok_p: bool
				if length_text == "-" {
					length = -1
				} else {
					length, ok_p = strconv.parse_int(length_text)
					assert(ok_p)
				}
			}
		}

		if length == -1 {
			err = field_error(field, "Only fixed arrays are supported.")
			return
		}

		field.array = Array_Field {
			length              = length,
			element_type        = element_t,
			element_type_string = element_t_str,
		}
	}
	return field, ""
}

parse_field_type :: proc(node: ^ast.Expr) -> (Field_Type, string) {
	assert(node != nil)

	field_type: Field_Type = .None
	#partial switch n in node.derived {
	case ^ast.Ident:
		return odin_type_to_field_type(n.name), n.name
	case ^ast.Selector_Expr:
		return odin_type_to_field_type(n.field.name), n.field.name
	case ^ast.Array_Type:
		return .Array, "array"
	}

	return .None, ""
}

calculate_padding_by_memeory_layout :: proc(layout: Memory_Layout, d: Parse_Data, fields: []Field) -> []Field {
	switch layout {
	case .Std140:
		return _calculate_std140_layout(d, fields)
	case .Std430:
		return _calculate_std430_layout(d, fields)
	}
	return fields
}

_calculate_std140_layout :: proc(d: Parse_Data, fields: []Field) -> []Field {
	std140_fields := make([dynamic]Field)
	current_offset := 0

	pad_index := 0

	for field in fields {
		align := get_field_base_alignment_std140(d, field)
		size := get_field_type_size(d, field, .Std140)

		padding := (align - (current_offset % align)) % align

		if padding > 0 {
			assert(padding % 4 == 0, "Padding must be multiple of 4")
			for i in 0 ..< padding / 4 {
				append(&std140_fields, Field{name = fmt.aprintf("pad%d", pad_index), type = .Float})
				pad_index += 1
			}
			current_offset += padding
		}

		append(&std140_fields, field)
		current_offset += size
	}

	final_padding := (16 - (current_offset % 16)) % 16
	for i in 0 ..< final_padding / 4 {
		append(&std140_fields, Field{name = fmt.aprintf("pad%d", pad_index), type = .Float})
		pad_index += 1
	}

	return std140_fields[:]
}

_calculate_std430_layout :: proc(d: Parse_Data, fields: []Field) -> []Field {
	std430_fields := make([dynamic]Field)
	current_offset := 0

	pad_index := 0

	max_alig: int
	for field in fields {
		alig := get_field_base_alignment_std430(d, field)
		if alig > max_alig do max_alig = alig
	}

	for field in fields {
		align := get_field_base_alignment_std430(d, field)
		size := get_field_type_size(d, field, .Std430)

		padding := (align - (current_offset % align)) % align

		if padding > 0 {
			assert(padding % 4 == 0, "Padding must be multiple of 4")
			for i in 0 ..< padding / 4 {
				append(&std430_fields, Field{name = fmt.aprintf("pad%d", pad_index), type = .Float})
				pad_index += 1
			}
			current_offset += padding
		}

		append(&std430_fields, field)
		current_offset += size
	}

	final_padding := (max_alig - (current_offset % max_alig)) % max_alig
	for i in 0 ..< final_padding / 4 {
		append(&std430_fields, Field{name = fmt.aprintf("pad%d", pad_index), type = .Float})
		pad_index += 1
	}

	return std430_fields[:]
}

odin_type_to_field_type :: proc(str: string) -> Field_Type {
	switch str {
	case "i32":
		return .Int
	case "f32":
		return .Float
	case "b32":
		return .Bool
	case "vec2":
		return .Vector2
	case "vec3":
		return .Vector3
	case "vec4":
		return .Vector4
	case "mat4":
		return .Mat4
	case "Texture":
		return .Texture
	case "Buffer":
		return .Buffer
	case:
		return .None
	}
}

field_to_glsl_type :: proc(field: Field) -> string {
	switch field.type {
	case .None:
		return ""
	case .Int:
		return "int"
	case .Float:
		return "float"
	case .Bool:
		return "bool"
	case .Vector2:
		return "vec2"
	case .Vector3:
		return "vec3"
	case .Vector4:
		return "vec4"
	case .Mat4:
		return "mat4"
	case .Texture:
		return "uint"
	case .Buffer:
		return "uint"
	case .Array:
		type_string := field_to_glsl_type(
			Field{type = field.array.element_type, type_string = field.array.element_type_string},
		)
		if field.array.length != -1 {
			return fmt.aprintf("%s[%d]", type_string, field.array.length)
		}
		return fmt.aprintf("%s[]", type_string)
	case .Custom:
		return get_glsl_struct_name(field.type_string)
	}

	return ""
}

field_to_odin_type :: proc(field: Field, gfx_pref: string) -> string {
	switch field.type {
	case .None:
		return ""
	case .Int:
		return "i32"
	case .Float:
		return "f32"
	case .Bool:
		return "b32"
	case .Vector2:
		return "glsl.vec2"
	case .Vector3:
		return "glsl.vec3"
	case .Vector4:
		return "glsl.vec4"
	case .Mat4:
		return "glsl.mat4"
	case .Texture:
		return fmt.aprintf("%sTexture", gfx_pref)
	case .Buffer:
		return fmt.aprintf("%sBuffer", gfx_pref)
	case .Array:
		type_string := field_to_odin_type(
			Field{type = field.array.element_type, type_string = field.array.element_type_string},
			gfx_pref,
		)
		if field.array.length == -1 {
			return fmt.aprintf("[]%s", type_string)
		}
		return fmt.aprintf("[%d]%s", field.array.length, type_string)
	case .Custom:
		return field.type_string
	}

	return ""
}

get_field_base_alignment_std140 :: proc(d: Parse_Data, field: Field) -> int {
	switch field.type {
	case .None:
		return 0
	case .Float, .Int, .Bool, .Texture, .Buffer:
		return 4
	case .Vector2:
		return 8
	case .Vector3, .Vector4, .Mat4:
		return 16
	case .Array, .Custom:
		return 16
	}
	return 16
}

get_field_base_alignment_std430 :: proc(d: Parse_Data, field: Field) -> int {
	switch field.type {
	case .None:
		return 0
	case .Float, .Int, .Bool, .Texture, .Buffer:
		return 4
	case .Vector2:
		return 8
	case .Vector3, .Vector4, .Mat4:
		return 16
	case .Array:
		return get_field_base_alignment_std430(
			d,
			Field{type = field.array.element_type, type_string = field.array.element_type_string},
		)
	case .Custom:
		s, ok := d.structures[field.type_string]
		assert(ok)
		max := 0
		for field in s.fields {
			if max < get_field_base_alignment_std430(d, field) {
				max = get_field_base_alignment_std430(d, field)
			}
		}
		return max
	}
	return 16
}

get_field_type_size :: proc(d: Parse_Data, field: Field, memory_layout: Memory_Layout, loc := #caller_location) -> int {
	switch field.type {
	case .None:
		return 0
	case .Float, .Int, .Bool, .Texture, .Buffer:
		return 4
	case .Vector2:
		return 8
	case .Vector3:
		return 12
	case .Vector4:
		return 16
	case .Mat4:
		return 64
	case .Array:
		return(
			field.array.length *
			get_field_type_size(
				d,
				Field{type = field.array.element_type, type_string = field.array.element_type_string},
				memory_layout,
			) \
		)
	case .Custom:
		s, ok := d.structures[field.type_string]
		assert(ok, loc = loc)
		size := 0
		for field in calculate_padding_by_memeory_layout(memory_layout, d, s.fields) {
			size += get_field_type_size(d, field, memory_layout)
		}
		return size
	}
	return 0
}

parse_package_info :: proc(source: string) -> Ve_Package_Info {
	gfx_pkg_info := Ve_Package_Info{}

	s, _ := strings.split(source, " ")
	if len(s) > 2 {
		log.error(
			`Invalid ve_import format.
Expected:
	ve_import = "alias path"
	ve_import = "path"
	ve_import = ""

Examples:
	"ve"
	"ve libs/ve"
	""

But got:`,
			source,
		)
	}

	if len(s) == 1 {
		return Ve_Package_Info{alias = "", path = source}
	} else if len(s) == 2 {
		return Ve_Package_Info{alias = s[0], path = s[1]}
	}
	return Ve_Package_Info{}
}
